# Generated by Django 5.2.6 on 2026-05-12 15:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationlog',
            name='failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='provider_status_payload',
            field=models.JSONField(blank=True, help_text='Latest webhook/status payload from provider.', null=True),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='whatsapp_billable',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='whatsapp_conversation_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='whatsapp_display_phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='whatsapp_phone_number_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='whatsapp_pricing_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='whatsapp_pricing_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='whatsapp_recipient_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='communicationlog',
            name='provider_message_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='communicationlog',
            index=models.Index(fields=['channel'], name='communicati_channel_b6f991_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationlog',
            index=models.Index(fields=['status'], name='communicati_status_2ef9bb_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationlog',
            index=models.Index(fields=['related_model', 'related_object_id'], name='communicati_related_60d229_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationlog',
            index=models.Index(fields=['provider_message_id'], name='communicati_provide_df4e9e_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationlog',
            index=models.Index(fields=['recipient_contact'], name='communicati_recipie_0bab86_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationlog',
            index=models.Index(fields=['created_at'], name='communicati_created_5c9e16_idx'),
        ),
    ]
