# Generated by Django 5.2.6 on 2026-05-13 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_communicationlog_failed_at_and_more'),
        ('invoices', '0010_alter_invoice_public_token'),
        ('orders', '0011_quotation_public_decision_ip_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=20)),
                ('template_name', models.CharField(max_length=100)),
                ('message_type', models.CharField(choices=[('quotation', 'Quotation'), ('invoice', 'Invoice'), ('payment_reminder', 'Payment Reminder')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('whatsapp_message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('response_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.invoice')),
                ('quotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.quotation')),
            ],
        ),
    ]
