# Generated by Django 5.2.6 on 2026-09-03 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0004_emaillog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='communication_docs/%Y/%m/')),
                ('filename', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('communication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='communications.communicationlog')),
            ],
        ),
    ]
