# Generated by Django 5.2.6 on 2026-01-18 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('consumers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Internal role code, e.g. rep, supervisor', max_length=30, unique=True)),
                ('name', models.CharField(help_text='Human readable role name', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_type', models.CharField(choices=[('CONSUMER', 'Consumer'), ('BUSINESS', 'Business')], db_index=True, default='CONSUMER', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', help_text='Approval state of this profile.', max_length=8)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('display_name', models.CharField(blank=True, help_text='How we should address you on documents/communication.', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_seen_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('client', models.ForeignKey(blank=True, help_text='Required when profile type is Business.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_profiles', to='clients.client')),
                ('consumer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_profile', to='consumers.consumer')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='pending', help_text='Approval state of this profile.', max_length=8)),
                ('department', models.CharField(blank=True, choices=[('Operations', 'Operations'), ('Sales', 'Sales'), ('Logistics', 'Logistics'), ('Management', 'Management')], help_text='Staff department (optional).', max_length=20, null=True)),
                ('can_access_sales', models.BooleanField(default=False, help_text='Allow this staff member to access the Sales portal.')),
                ('auth_code_hash', models.CharField(blank=True, help_text='Hashed staff authorisation code; set via admin form.', max_length=128, verbose_name='authorisation code (hashed)')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_seen_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SalesRepProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='pending', help_text='Approval state of this profile.', max_length=8)),
                ('auth_code_hash', models.CharField(blank=True, help_text='Hashed staff authorisation code; set via admin form.', max_length=128, verbose_name='authorisation code (hashed)')),
                ('department', models.CharField(default='Sales', help_text='Department for this sales rep.', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_seen_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('supervisor', models.ForeignKey(blank=True, help_text='Supervisor/manager responsible for this sales rep.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_reps', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sales_rep_profile', to=settings.AUTH_USER_MODEL)),
                ('roles', models.ManyToManyField(blank=True, help_text='Roles this sales user fulfills (rep, supervisor, or both).', related_name='sales_profiles', to='profiles.salesrole')),
                ('staff_profile', models.OneToOneField(blank=True, help_text='Link to the staff profile (every sales rep must have a staff profile).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_profile', to='profiles.staffprofile')),
            ],
        ),
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], db_index=True, default='pending', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
                ('staff_profile', models.OneToOneField(help_text='Every driver must also be a staff member.', on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to='profiles.staffprofile')),
            ],
        ),
    ]
