# Generated by Django 5.2.6 on 2026-04-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesrepprofile',
            name='department',
            field=models.CharField(default='SALES', help_text='Department for this sales rep.', max_length=50),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='department',
            field=models.CharField(blank=True, choices=[('SUPPORT', 'Support'), ('ACCOUNTS', 'Accounts'), ('SALES', 'Sales'), ('COMPLIANCE', 'Compliance'), ('SUPPLY_CHAIN', 'Supply Chain'), ('OPERATIONS', 'Operations'), ('LOGISTICS', 'Logistics'), ('FINANCE', 'Finance')], help_text='Staff department (optional).', max_length=20, null=True),
        ),
    ]
