# Generated by Django 5.2.6 on 2025-10-27 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_client_price_type'),
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_type', models.CharField(choices=[('PERSONAL', 'Personal'), ('BUSINESS', 'Business')], db_index=True, default='PERSONAL', max_length=10)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('display_name', models.CharField(blank=True, help_text='How we should address you on documents/communication.', max_length=120)),
                ('company_name', models.CharField(blank=True, max_length=160)),
                ('tax_number', models.CharField(blank=True, max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, help_text='Required when profile type is Business.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='clients.client')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
