# Generated by Django 5.2.6 on 2026-05-27 15:55

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_salesrepprofile_department_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Registered or trading name of the sales operator.', max_length=255, unique=True)),
                ('territory', models.CharField(choices=[('SOUTH_WEST', 'South / West'), ('EAST', 'East'), ('NORTH_CENTRAL', 'North / Central'), ('MIDVAAL', 'Midvaal'), ('PRETORIA', 'Pretoria'), ('OTHER', 'Other')], db_index=True, help_text='Assigned operating territory.', max_length=20)),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('suburb', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=120)),
                ('province', models.CharField(max_length=120)),
                ('postal_code', models.CharField(max_length=20)),
                ('bank_name', models.CharField(max_length=120)),
                ('account_holder', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=50)),
                ('branch_code', models.CharField(max_length=20)),
                ('account_type', models.CharField(choices=[('CHEQUE', 'Cheque'), ('SAVINGS', 'Savings'), ('BUSINESS', 'Business')], default='CHEQUE', max_length=20)),
                ('base_commission_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Standard commission percentage paid to this operator.', max_digits=5)),
                ('bonus_commission_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Additional bonus commission percentage paid when targets or conditions are met.', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_1', models.ForeignKey(help_text='Primary owner/user linked to this operator.', on_delete=django.db.models.deletion.PROTECT, related_name='primary_sales_operators', to=settings.AUTH_USER_MODEL)),
                ('owner_2', models.ForeignKey(blank=True, help_text='Secondary owner/user linked to this operator (optional).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='secondary_sales_operators', to=settings.AUTH_USER_MODEL)),
                ('responsible_user_1', models.ForeignKey(blank=True, help_text='Primary internal user responsible for managing this sales operator.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_managed_sales_operators', to=settings.AUTH_USER_MODEL)),
                ('responsible_user_2', models.ForeignKey(blank=True, help_text='Secondary internal user responsible for managing this sales operator.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_managed_sales_operators', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sales Operator',
                'verbose_name_plural': 'Sales Operators',
                'ordering': ['name'],
            },
        ),
    ]
