# Generated by Django 5.2.6 on 2025-10-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_customerprofile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='pending', help_text='Approval state of this profile.', max_length=8),
        ),
    ]
