# Generated by Django 5.2.6 on 2026-05-27 15:59

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_salesoperator'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrepprofile',
            name='base_commission_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Standard commission percentage paid to this sales rep.', max_digits=5),
        ),
        migrations.AddField(
            model_name='salesrepprofile',
            name='bonus_commission_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Additional bonus commission percentage paid when targets or conditions are met.', max_digits=5),
        ),
        migrations.AddField(
            model_name='salesrepprofile',
            name='sales_operator',
            field=models.ForeignKey(blank=True, help_text='Sales operator this sales rep belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_reps', to='profiles.salesoperator'),
        ),
    ]
