# Generated by Django 5.2.6 on 2025-10-30 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_staffprofile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
