# Generated by Django 5.2.6 on 2026-06-11 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesrepprofile',
            name='department',
            field=models.CharField(blank=True, default='SALES', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profiles', to='profiles.department'),
        ),
    ]
