# Generated by Django 5.2.6 on 2026-06-11 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_salesrepprofile_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='staff_members', to='profiles.department'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='primary_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_staff_profiles', to='profiles.department'),
        ),
    ]
