# Generated by Django 5.2.6 on 2025-11-16 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_salesrepprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='can_access_sales',
            field=models.BooleanField(default=False, help_text='Allow this staff member to access the Sales portal.'),
        ),
    ]
