# Generated by Django 5.2.6 on 2026-06-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_staffprofile_departments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='department',
        ),
        migrations.AddField(
            model_name='department',
            name='email',
            field=models.EmailField(blank=True, help_text='Department email address.', max_length=254, null=True),
        ),
    ]
