# Generated by Django 5.2.6 on 2025-11-19 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_staffprofile_can_access_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='department',
            field=models.CharField(blank=True, choices=[('Operations', 'Operations'), ('Sales', 'Sales'), ('Logistics', 'Logistics'), ('Management', 'Management')], help_text='Staff department (optional).', max_length=20, null=True),
        ),
    ]
