# Generated by Django 5.2.6 on 2025-11-19 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_staffprofile_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrepprofile',
            name='staff_profile',
            field=models.OneToOneField(blank=True, help_text='Link to the staff profile (every sales rep must have a staff profile).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_profile', to='profiles.staffprofile'),
        ),
        migrations.AlterField(
            model_name='salesrepprofile',
            name='department',
            field=models.CharField(default='Sales', help_text='Department for this sales rep.', max_length=50),
        ),
    ]
