# Generated by Django 5.2.6 on 2026-08-17 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0031_remove_client_categories_remove_lead_interested_in_and_more'),
        ('profiles', '0008_remove_staffprofile_department_department_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrepprofile',
            name='region',
            field=models.ForeignKey(blank=True, help_text='Region assigned to this sales user.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_profiles', to='clients.region'),
        ),
        migrations.AddField(
            model_name='salesrepprofile',
            name='territory',
            field=models.ForeignKey(blank=True, help_text='Territory assigned to this sales user.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_profiles', to='clients.territory'),
        ),
    ]
