# Generated by Django 5.2.6 on 2026-08-26 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_salesrepprofile_region_salesrepprofile_territory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesrepprofile',
            name='supervisor',
            field=models.ForeignKey(blank=True, help_text='Staff member responsible for this sales rep. The supervisor may also be the rep themselves.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_sales_reps', to='profiles.staffprofile'),
        ),
    ]
