# Generated by Django 5.2.6 on 2025-12-07 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_salesrepprofile_staff_profile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrepprofile',
            name='supervisor',
            field=models.ForeignKey(blank=True, help_text='Supervisor/manager responsible for this sales rep.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_reps', to=settings.AUTH_USER_MODEL),
        ),
    ]
