# Generated by Django 5.2.6 on 2025-12-13 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_prospectupdate_negotiation_competitor_info_and_more'),
        ('consumers', '0001_initial'),
        ('profiles', '0010_salesrepprofile_supervisor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='tax_number',
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='consumer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_profile', to='consumers.consumer'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Required when profile type is Business.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_profiles', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='profile_type',
            field=models.CharField(choices=[('CONSUMER', 'Consumer'), ('BUSINESS', 'Business')], db_index=True, default='CONSUMER', max_length=10),
        ),
    ]
