# Generated by Django 5.2.6 on 2026-08-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_alter_salesrepprofile_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='address_line_1',
            field=models.CharField(blank=True, help_text="Driver's primary residential address.", max_length=255),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text="Latitude of the driver's address.", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text="Longitude of the driver's address.", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='province',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='suburb',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
