# Generated by Django 5.2.6 on 2025-12-22 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_remove_customerprofile_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', help_text='Approval state of this profile.', max_length=8),
        ),
    ]
