# Generated by Django 5.2.6 on 2026-09-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0032_lead_latitude_lead_location_captured_at_and_more'),
        ('profiles', '0011_driverprofile_address_line_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrepprofile',
            name='funeral_parlours',
            field=models.ManyToManyField(blank=True, limit_choices_to={'client_type': 'FUNERAL_PARLOUR'}, related_name='funeral_consultants', to='clients.client'),
        ),
        migrations.AddField(
            model_name='salesrepprofile',
            name='is_funeral_consultant',
            field=models.BooleanField(default=False, verbose_name='Funeral Parlour Consultant'),
        ),
    ]
