# Generated by Django 5.2.6 on 2026-01-05 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_alter_customerprofile_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Internal role code, e.g. rep, supervisor', max_length=30, unique=True)),
                ('name', models.CharField(help_text='Human readable role name', max_length=50)),
            ],
        ),
    ]
