# Generated by Django 5.2.6 on 2026-01-05 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_salesrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrepprofile',
            name='roles',
            field=models.ManyToManyField(blank=True, help_text='Roles this sales user fulfills (rep, supervisor, or both).', related_name='sales_profiles', to='profiles.salesrole'),
        ),
    ]
