# Generated by Django 5.2.6 on 2025-09-12 14:05

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(help_text='Short internal code, e.g. HENLEY, BRM', max_length=20, unique=True)),
                ('categories', models.CharField(blank=True, help_text="Comma-separated tags (optional), e.g. 'poultry, sauces'", max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('contact_person', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('whatsapp', models.CharField(blank=True, max_length=50)),
                ('website', models.URLField(blank=True)),
                ('address_line1', models.CharField(blank=True, max_length=200)),
                ('address_line2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('province', models.CharField(blank=True, max_length=120)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(default='South Africa', max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('terms_type', models.CharField(choices=[('STANDARD', 'Standard (COD/7D/14D/30D/45D/60D)'), ('DEPOSIT_SPLIT', 'Deposit + Balance (e.g., 30% upfront)')], default='STANDARD', max_length=20)),
                ('payment_terms', models.CharField(blank=True, choices=[('COD', 'Cash on Delivery'), ('7D', '7 days'), ('14D', '14 days'), ('30D', '30 days'), ('45D', '45 days'), ('60D', '60 days')], default='30D', max_length=10)),
                ('deposit_percent', models.DecimalField(decimal_places=2, default=Decimal('30.00'), help_text='Percentage due before delivery (e.g., 30.00 for 30%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('balance_due_days', models.PositiveIntegerField(default=7, help_text='Days after delivery to pay remaining balance (e.g., 3 or 7)')),
                ('vat_number', models.CharField(blank=True, max_length=80)),
                ('company_reg_number', models.CharField(blank=True, max_length=80)),
                ('contract_file', models.FileField(blank=True, null=True, upload_to='supplier_docs/contracts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_manager', models.ForeignKey(blank=True, help_text='Internal staff member managing this account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='suppliers_s_code_d1984e_idx'), models.Index(fields=['name'], name='suppliers_s_name_6277a9_idx'), models.Index(fields=['is_active'], name='suppliers_s_is_acti_a75d30_idx')],
            },
        ),
    ]
