# Generated by Django 5.2.6 on 2025-09-14 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_initial'),
        ('suppliers', '0002_delete_supplier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(help_text='Short internal code, e.g. HENLEY, BRM', max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('contact_person', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('whatsapp', models.CharField(blank=True, max_length=50)),
                ('website', models.URLField(blank=True)),
                ('address_line1', models.CharField(blank=True, max_length=200)),
                ('address_line2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('province', models.CharField(blank=True, max_length=120)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(default='South Africa', max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('payment_terms', models.CharField(blank=True, choices=[('COD', 'Cash on Delivery'), ('3D', '3 days'), ('7D', '7 days'), ('14D', '14 days'), ('30D', '30 days')], default='COD', max_length=10)),
                ('vat_number', models.CharField(blank=True, max_length=80)),
                ('company_reg_number', models.CharField(blank=True, max_length=80)),
                ('contract_file', models.FileField(blank=True, null=True, upload_to='supplier_docs/contracts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_manager', models.ForeignKey(blank=True, help_text='Internal staff member managing this account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_accounts', to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(blank=True, help_text='Select one or more product categories this supplier provides.', related_name='suppliers', to='products.category')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='suppliers_s_code_d1984e_idx'), models.Index(fields=['name'], name='suppliers_s_name_6277a9_idx'), models.Index(fields=['is_active'], name='suppliers_s_is_acti_a75d30_idx')],
            },
        ),
    ]
