# Generated by Django 5.2.6 on 2025-10-31 13:07

import image_cropping.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload a raster logo (PNG/JPG). Transparent PNG recommended.', null=True, upload_to='supplier_docs/logos/'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='logo_cropping',
            field=image_cropping.fields.ImageRatioField('logo', '400x200', adapt_rotation=False, allow_fullsize=False, free_crop=True, help_text=None, hide_image_field=False, size_warning=False, verbose_name='logo cropping'),
        ),
    ]
