# Generated by Django 5.2.6 on 2025-10-31 13:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_productvariant'),
        ('suppliers', '0004_supplier_logo_supplier_logo_cropping'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='visible',
            field=models.BooleanField(db_index=True, default=False, help_text='If Yes, this supplier can be shown publicly (e.g., in the Brands slider).'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['visible'], name='suppliers_s_visible_8fbb2e_idx'),
        ),
    ]
