# Generated by Django 5.2.6 on 2026-01-18 22:16

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_index=True)),
                ('month', models.IntegerField(db_index=True)),
                ('recurring_sales_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('recurring_commission_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('new_business_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('new_business_commission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('weekly_average', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('commission_rate_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Effective commission % on recurring cost (for reporting).', max_digits=5)),
                ('monthly_cash_bonus', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_payout', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('paid', models.BooleanField(default=False)),
                ('paid_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='CommissionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total COST of products on invoice (ex VAT).', max_digits=14)),
                ('rep_rate', models.DecimalField(choices=[(Decimal('1.00'), '1%'), (Decimal('1.50'), '1.5%'), (Decimal('2.00'), '2%'), (Decimal('2.50'), '2.5%'), (Decimal('3.00'), '3%'), (Decimal('3.50'), '3.5%'), (Decimal('4.00'), '4%')], decimal_places=2, default=Decimal('3.50'), help_text='Commission percent for sales rep (on cost).', max_digits=5)),
                ('rep_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('supervisor_rate', models.DecimalField(choices=[(Decimal('1.00'), '1%'), (Decimal('1.50'), '1.5%'), (Decimal('2.00'), '2%'), (Decimal('2.50'), '2.5%'), (Decimal('3.00'), '3%'), (Decimal('3.50'), '3.5%'), (Decimal('4.00'), '4%')], decimal_places=2, default=Decimal('1.00'), help_text='Commission percent for supervisor (on cost).', max_digits=5)),
                ('supervisor_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('is_new_business', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rep', models.ForeignKey(blank=True, help_text='Snapshot of the sales rep who owned the client when commission was generated.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_entries', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(blank=True, help_text='Snapshot of the supervisor at commission time (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor_commission_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyOverdueSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_date', models.DateField(db_index=True, unique=True)),
                ('new_overdue', models.IntegerField(default=0)),
                ('total_overdue', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-run_date'],
                'indexes': [models.Index(fields=['run_date'], name='invoices_da_run_dat_08289c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partially Paid'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='unpaid', max_length=20)),
                ('invoice_date', models.DateField(default=django.utils.timezone.localdate)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('paid_date', models.DateField(blank=True, db_index=True, help_text='Date invoice reached fully-paid deposit status.', null=True)),
                ('order_total_inc', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('amount_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Deposit due (cash portion).', max_digits=12)),
                ('deposit_required', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('deposit_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('credit_used', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Portion going onto credit (after deposit).', max_digits=12)),
                ('credit_usage_applied', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='(Deprecated) Old delta tracker when pushing to ledger directly.', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='clients.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
