# Generated by Django 5.2.6 on 2026-01-18 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoices', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='orders.order'),
        ),
        migrations.AddField(
            model_name='commissionentry',
            name='invoice',
            field=models.OneToOneField(help_text='Invoice that generated this commission entry (created when invoice is paid).', on_delete=django.db.models.deletion.CASCADE, related_name='commission_entry', to='invoices.invoice'),
        ),
        migrations.AddField(
            model_name='monthlycommission',
            name='rep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_commissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commissionadjustment',
            name='monthly_commission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='invoices.monthlycommission'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='invoices_in_status_cec546_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_date'], name='invoices_in_invoice_087f87_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['client', 'status'], name='invoices_in_client__d0ba52_idx'),
        ),
        migrations.AddIndex(
            model_name='commissionentry',
            index=models.Index(fields=['rep'], name='invoices_co_rep_id_0b6a77_idx'),
        ),
        migrations.AddIndex(
            model_name='commissionentry',
            index=models.Index(fields=['supervisor'], name='invoices_co_supervi_91958b_idx'),
        ),
        migrations.AddIndex(
            model_name='commissionentry',
            index=models.Index(fields=['is_new_business'], name='invoices_co_is_new__e18368_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='monthlycommission',
            unique_together={('rep', 'year', 'month')},
        ),
    ]
