# Generated by Django 5.2.6 on 2025-09-18 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_account_type_alter_client_credit_status'),
        ('invoices', '0002_dailyoverduesummary'),
        ('orders', '0004_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyoverduesummary',
            options={'ordering': ['-run_date']},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='dailyoverduesummary',
            index=models.Index(fields=['run_date'], name='invoices_da_run_dat_08289c_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='invoices_in_status_cec546_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_date'], name='invoices_in_invoice_087f87_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['client', 'status'], name='invoices_in_client__d0ba52_idx'),
        ),
    ]
