# Generated by Django 5.2.6 on 2026-02-22 06:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='invoice',
            name='invoices_in_status_cec546_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='invoices_in_invoice_087f87_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='invoices_in_client__d0ba52_idx',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='credit_usage_applied',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount_due',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='credit_used',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='paid_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
