# Generated by Django 5.2.6 on 2025-09-18 12:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_alter_dailyoverduesummary_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='credit_usage_applied',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Amount of this invoice's credit already pushed to client's credit ledger.", max_digits=12),
        ),
    ]
