# Generated by Django 5.2.6 on 2026-02-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_rename_company_reg_number_clientcompliance_registration_identifier_and_more'),
        ('invoices', '0003_remove_invoice_invoices_in_status_cec546_idx_and_more'),
        ('orders', '0004_alter_order_status_orderaudit'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='dailyoverduesummary',
            name='invoices_da_run_dat_08289c_idx',
        ),
        migrations.AddField(
            model_name='invoice',
            name='commission_generated_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when commission was first generated. Prevents regeneration.', null=True),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='invoices_in_status_cec546_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_date'], name='invoices_in_invoice_087f87_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['client', 'status'], name='invoices_in_client__d0ba52_idx'),
        ),
    ]
