# Generated by Django 5.2.6 on 2026-02-24 01:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_remove_dailyoverduesummary_invoices_da_run_dat_08289c_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='commission_generated_at',
        ),
        migrations.AddField(
            model_name='invoice',
            name='credit_usage_applied',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='(Deprecated) Old delta tracker when pushing to ledger directly.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount_due',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Deposit due (cash portion).', max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='credit_used',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Portion going onto credit (after deposit).', max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='paid_date',
            field=models.DateField(blank=True, db_index=True, help_text='Date invoice reached fully-paid deposit status.', null=True),
        ),
        migrations.AddIndex(
            model_name='dailyoverduesummary',
            index=models.Index(fields=['run_date'], name='invoices_da_run_dat_08289c_idx'),
        ),
    ]
