# Generated by Django 5.2.6 on 2025-11-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_invoice_credit_usage_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='paid_date',
            field=models.DateField(blank=True, db_index=True, help_text='Date invoice reached fully-paid status (deposit met).', null=True),
        ),
    ]
