# Generated by Django 5.2.6 on 2026-02-27 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_remove_invoice_commission_generated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UtilizationSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cycle_days', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['cycle_days'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('JAN', 'January'), ('FEB', 'February'), ('MAR', 'March'), ('APR', 'April'), ('MAY', 'May'), ('JUN', 'June'), ('JUL', 'July'), ('AUG', 'August'), ('SEP', 'September'), ('OCT', 'October'), ('NOV', 'November'), ('DEC', 'December')], max_length=3)),
                ('year', models.IntegerField(choices=[(2026, '2026'), (2027, '2027'), (2028, '2028'), (2029, '2029'), (2030, '2030')])),
                ('quarter', models.CharField(choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4')], max_length=2)),
                ('area', models.CharField(choices=[('NORTH_CENTRAL', 'North/Central'), ('SOUTH_WEST', 'South/West'), ('EAST', 'East')], max_length=20)),
                ('monthly_target', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-year', 'month'],
                'unique_together': {('month', 'year', 'area')},
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='segment',
            field=models.ForeignKey(blank=True, help_text='Utilization segment this invoice belongs to (Daily / 3-Day / 7-Day).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='invoices.utilizationsegment'),
        ),
        migrations.CreateModel(
            name='MonthlyTargetAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, help_text='Allocation percentage of total monthly target', max_digits=5)),
                ('monthly_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='invoices.monthlytarget')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoices.utilizationsegment')),
            ],
            options={
                'ordering': ['segment__cycle_days'],
                'unique_together': {('monthly_target', 'segment')},
            },
        ),
    ]
