# Generated by Django 5.2.6 on 2025-11-09 10:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_invoice_paid_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='credit_usage_applied',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='(Deprecated) Previously used as a delta tracker when pushing to ledger directly.', max_digits=12),
        ),
    ]
