# Generated by Django 5.2.6 on 2025-11-09 11:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_alter_invoice_credit_usage_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='credit_usage_applied',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='(Deprecated) Old delta tracker when pushing to ledger directly.', max_digits=12),
        ),
    ]
