# Generated by Django 5.2.6 on 2026-03-03 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_utilizationsegment_monthlytarget_invoice_segment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('ozow', 'Ozow')], max_length=20)),
                ('transaction_reference', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('raw_request', models.JSONField(blank=True, null=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_logs', to='invoices.invoice')),
            ],
        ),
    ]
