# Generated by Django 5.2.6 on 2025-11-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_alter_invoice_credit_usage_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='paid_date',
            field=models.DateField(blank=True, db_index=True, help_text='Date invoice reached fully-paid deposit status.', null=True),
        ),
    ]
