# Generated by Django 5.2.6 on 2026-03-11 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_paymentlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlog',
            name='provider',
            field=models.CharField(choices=[('ozow', 'Ozow'), ('yoco', 'Yoco')], max_length=20),
        ),
    ]
