# Generated by Django 5.2.6 on 2026-05-11 20:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_alter_paymentlog_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='public_token',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
