# Generated by Django 5.2.6 on 2025-11-18 12:37

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_alter_invoice_paid_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_index=True)),
                ('month', models.IntegerField(db_index=True)),
                ('recurring_sales_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('recurring_commission_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('new_business_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('new_business_commission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('weekly_average', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('commission_rate_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('monthly_cash_bonus', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_payout', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('paid', models.BooleanField(default=False)),
                ('paid_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_commissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('rep', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='CommissionAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('monthly_commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='invoices.monthlycommission')),
            ],
        ),
        migrations.CreateModel(
            name='CommissionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Commission percent (e.g. 5.00 for 5%).', max_digits=5)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('is_new_business', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.OneToOneField(help_text='Invoice that generated this commission entry (created when invoice is paid).', on_delete=django.db.models.deletion.CASCADE, related_name='commission_entry', to='invoices.invoice')),
                ('rep', models.ForeignKey(blank=True, help_text='Snapshot of the sales rep who owned the client when commission was generated.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['rep'], name='invoices_co_rep_id_0b6a77_idx'), models.Index(fields=['is_new_business'], name='invoices_co_is_new__e18368_idx')],
            },
        ),
    ]
