# Generated by Django 5.2.6 on 2025-12-07 15:58

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0009_monthlycommission_commissionadjustment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='commissionentry',
            old_name='amount',
            new_name='rep_amount',
        ),
        migrations.RenameField(
            model_name='commissionentry',
            old_name='invoice_total',
            new_name='supervisor_amount',
        ),
        migrations.RemoveField(
            model_name='commissionentry',
            name='rate',
        ),
        migrations.AddField(
            model_name='commissionentry',
            name='cost_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total COST of products on invoice (ex VAT).', max_digits=14),
        ),
        migrations.AddField(
            model_name='commissionentry',
            name='rep_rate',
            field=models.DecimalField(choices=[(Decimal('1.00'), '1%'), (Decimal('1.50'), '1.5%'), (Decimal('2.00'), '2%'), (Decimal('2.50'), '2.5%'), (Decimal('3.00'), '3%'), (Decimal('3.50'), '3.5%'), (Decimal('4.00'), '4%')], decimal_places=2, default=Decimal('3.50'), help_text='Commission percent for sales rep (on cost).', max_digits=5),
        ),
        migrations.AddField(
            model_name='commissionentry',
            name='supervisor',
            field=models.ForeignKey(blank=True, help_text='Snapshot of the supervisor at commission time (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor_commission_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commissionentry',
            name='supervisor_rate',
            field=models.DecimalField(choices=[(Decimal('1.00'), '1%'), (Decimal('1.50'), '1.5%'), (Decimal('2.00'), '2%'), (Decimal('2.50'), '2.5%'), (Decimal('3.00'), '3%'), (Decimal('3.50'), '3.5%'), (Decimal('4.00'), '4%')], decimal_places=2, default=Decimal('1.00'), help_text='Commission percent for supervisor (on cost).', max_digits=5),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount_due',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Deposit due (cash portion).', max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='credit_used',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Portion going onto credit (after deposit).', max_digits=12),
        ),
        migrations.AlterField(
            model_name='monthlycommission',
            name='commission_rate_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Effective commission % on recurring cost (for reporting).', max_digits=5),
        ),
        migrations.AddIndex(
            model_name='commissionentry',
            index=models.Index(fields=['supervisor'], name='invoices_co_supervi_91958b_idx'),
        ),
    ]
