# Generated by Django 5.2.6 on 2026-05-25 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0010_alter_invoice_public_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlytarget',
            name='client_target',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlytarget',
            name='client_target_reached_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlytarget',
            name='monthly_target_reached_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='MonthlyTargetAllocation',
        ),
    ]
