# Generated by Django 5.2.6 on 2026-05-25 20:14

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0011_monthlytarget_client_target_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyTargetAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_target_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Rand value target assigned to this sales rep for the month.', max_digits=14)),
                ('client_target', models.PositiveIntegerField(default=0, help_text='Number of new recurring clients this sales rep must achieve for the month.')),
                ('monthly_target_reached_at', models.DateTimeField(blank=True, help_text='Timestamp when the sales rep reached their monthly revenue target.', null=True)),
                ('client_target_reached_at', models.DateTimeField(blank=True, help_text='Timestamp when the sales rep reached their client target.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monthly_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rep_allocations', to='invoices.monthlytarget')),
                ('sales_rep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='monthly_target_allocations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sales_rep__first_name', 'sales_rep__last_name'],
                'unique_together': {('monthly_target', 'sales_rep')},
            },
        ),
    ]
