# Generated by Django 5.2.6 on 2026-05-25 20:38

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0012_monthlytargetallocation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlytarget',
            name='client_target',
        ),
        migrations.AddField(
            model_name='monthlytarget',
            name='total_client_target',
            field=models.PositiveIntegerField(default=0, help_text='Total new recurring client target for this month and area.'),
        ),
        migrations.AlterField(
            model_name='monthlytarget',
            name='client_target_reached_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the total client target was reached.', null=True),
        ),
        migrations.AlterField(
            model_name='monthlytarget',
            name='monthly_target',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total rand value target for this month and area.', max_digits=14),
        ),
        migrations.AlterField(
            model_name='monthlytarget',
            name='monthly_target_reached_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the total monthly revenue target was reached.', null=True),
        ),
        migrations.AlterField(
            model_name='monthlytargetallocation',
            name='sales_rep',
            field=models.ForeignKey(blank=True, help_text='Sales rep assigned to this monthly target allocation.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='monthly_target_allocations', to=settings.AUTH_USER_MODEL),
        ),
    ]
