# Generated by Django 5.2.6 on 2026-05-26 04:27

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0018_prospect_preferred_delivery_slot_1_and_more'),
        ('invoices', '0013_remove_monthlytarget_client_target_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionentry',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Snapshot of the client associated with this commission entry.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_entries', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='commissionentry',
            name='rep_rate',
            field=models.DecimalField(choices=[(Decimal('1.00'), '1%'), (Decimal('1.50'), '1.5%'), (Decimal('2.00'), '2%'), (Decimal('2.50'), '2.5%'), (Decimal('3.00'), '3%'), (Decimal('3.50'), '3.5%'), (Decimal('4.00'), '4%'), (Decimal('5.00'), '5%')], decimal_places=2, default=Decimal('3.50'), help_text='Commission percent for sales rep (on cost).', max_digits=5),
        ),
        migrations.AlterField(
            model_name='commissionentry',
            name='supervisor_rate',
            field=models.DecimalField(choices=[(Decimal('1.00'), '1%'), (Decimal('1.50'), '1.5%'), (Decimal('2.00'), '2%'), (Decimal('2.50'), '2.5%'), (Decimal('3.00'), '3%'), (Decimal('3.50'), '3.5%'), (Decimal('4.00'), '4%'), (Decimal('5.00'), '5%')], decimal_places=2, default=Decimal('1.00'), help_text='Commission percent for supervisor (on cost).', max_digits=5),
        ),
    ]
