# Generated by Django 5.2.6 on 2026-05-27 15:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0014_commissionentry_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissionentry',
            name='rep_rate',
            field=models.DecimalField(choices=[(Decimal('1.00'), '1%'), (Decimal('1.50'), '1.5%'), (Decimal('2.00'), '2%'), (Decimal('2.50'), '2.5%'), (Decimal('3.00'), '3%'), (Decimal('3.50'), '3.5%'), (Decimal('4.00'), '4%'), (Decimal('5.00'), '5%')], decimal_places=2, default=Decimal('2.50'), help_text='Commission percent for sales rep (on cost).', max_digits=5),
        ),
        migrations.AlterField(
            model_name='monthlytarget',
            name='area',
            field=models.CharField(choices=[('SOUTH_WEST', 'South / West'), ('EAST', 'East'), ('NORTH_CENTRAL', 'North / Central'), ('MIDVAAL', 'Midvaal'), ('PRETORIA', 'Pretoria'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
