# Generated by Django 5.2.6 on 2026-08-17 12:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0015_alter_commissionentry_rep_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissionentry',
            name='rep_rate',
            field=models.DecimalField(choices=[(Decimal('1.00'), '1%'), (Decimal('1.50'), '1.5%'), (Decimal('1.75'), '1.75%'), (Decimal('2.00'), '2%'), (Decimal('2.25'), '2.25%'), (Decimal('2.50'), '2.5%'), (Decimal('3.00'), '3%'), (Decimal('3.50'), '3.5%'), (Decimal('4.00'), '4%'), (Decimal('5.00'), '5%')], decimal_places=2, default=Decimal('2.25'), help_text='Commission percent for sales rep (on cost).', max_digits=5),
        ),
        migrations.AlterField(
            model_name='commissionentry',
            name='supervisor_rate',
            field=models.DecimalField(choices=[(Decimal('1.00'), '1%'), (Decimal('1.50'), '1.5%'), (Decimal('1.75'), '1.75%'), (Decimal('2.00'), '2%'), (Decimal('2.25'), '2.25%'), (Decimal('2.50'), '2.5%'), (Decimal('3.00'), '3%'), (Decimal('3.50'), '3.5%'), (Decimal('4.00'), '4%'), (Decimal('5.00'), '5%')], decimal_places=2, default=Decimal('1.75'), help_text='Commission percent for supervisor (on cost).', max_digits=5),
        ),
    ]
