# Generated by Django 5.2.6 on 2026-08-26 10:33

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0031_remove_client_categories_remove_lead_interested_in_and_more'),
        ('invoices', '0017_alter_monthlytarget_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlytarget',
            name='territory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='monthly_targets', to='clients.territory'),
        ),
        migrations.AlterField(
            model_name='monthlytarget',
            name='month',
            field=models.CharField(choices=[('JAN', 'January'), ('FEB', 'February'), ('MAR', 'March'), ('APR', 'April'), ('MAY', 'May'), ('JUN', 'June'), ('JUL', 'July'), ('AUG', 'August'), ('SEP', 'September'), ('OCT', 'October'), ('NOV', 'November'), ('DEC', 'December')], help_text='Month in which the reporting period ends on the 15th.', max_length=3),
        ),
        migrations.AlterField(
            model_name='monthlytarget',
            name='monthly_target',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total rand value target for this territory and reporting period.', max_digits=14),
        ),
        migrations.AlterField(
            model_name='monthlytarget',
            name='total_client_target',
            field=models.PositiveIntegerField(default=0, help_text='Total new recurring client target for this territory and reporting period.'),
        ),
    ]
