# Generated by Django 5.2.6 on 2026-08-26 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0031_remove_client_categories_remove_lead_interested_in_and_more'),
        ('invoices', '0018_monthlytarget_territory_alter_monthlytarget_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionentry',
            name='area',
            field=models.ForeignKey(blank=True, help_text='Area of the client at the time of commission.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_entries', to='clients.area'),
        ),
        migrations.AddField(
            model_name='commissionentry',
            name='territory',
            field=models.ForeignKey(blank=True, help_text='Territory of the client at the time of commission.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_entries', to='clients.territory'),
        ),
    ]
