# Generated by Django 5.2.6 on 2026-08-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0019_commissionentry_area_commissionentry_territory'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionentry',
            name='period_end',
            field=models.DateField(blank=True, help_text='End date of the commission period.', null=True),
        ),
        migrations.AddField(
            model_name='commissionentry',
            name='period_start',
            field=models.DateField(blank=True, help_text='Start date of the commission period.', null=True),
        ),
    ]
