# Generated by Django 5.2.6 on 2026-08-26 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0020_commissionentry_period_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commissionentry',
            name='period_end',
        ),
        migrations.RemoveField(
            model_name='commissionentry',
            name='period_start',
        ),
        migrations.AddField(
            model_name='commissionentry',
            name='period',
            field=models.CharField(blank=True, editable=False, help_text='Commission period, e.g. 15 Aug - 14 Sep.', max_length=50),
        ),
    ]
