# Generated by Django 5.2.6 on 2026-09-12 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0033_enduser'),
        ('invoices', '0021_remove_commissionentry_period_end_and_more'),
        ('orders', '0012_order_end_user_quotation_end_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='end_user',
            field=models.ForeignKey(blank=True, help_text='End user receiving or benefiting from this invoice.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='clients.enduser'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['end_user', 'status'], name='invoices_in_end_use_75b338_idx'),
        ),
    ]
