"""
Django settings for seshibo_site project.

Generated by 'django-admin startproject' using Django 5.2.6.
"""

from pathlib import Path
import os
from celery.schedules import crontab
from dotenv import load_dotenv


BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(dotenv_path=BASE_DIR / ".env")


# ---------------------------
# BASE DIR
# ---------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# ---------------------------
# SECRET KEY & DEBUG
# ---------------------------
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "fallback-secret-key-for-dev")
DEBUG = os.getenv("DJANGO_DEBUG", "False") == "True"
DJANGO_ENV = os.getenv("DJANGO_ENV", "development")  # "production" when live

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", ".onrender.com,localhost,127.0.0.1").split(",")

# ---------------------------
# LOGIN URLS
# ---------------------------
LOGIN_URL = "/"
LOGIN_REDIRECT_URL = "/"

# ---------------------------
# INSTALLED APPS
# ---------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',

    # project apps
    'home',
    'staff_portal',
    'suppliers',
    'products',
    'clients',
    'orders',
    'invoices',
    'deliveries',
    'transactions',
    'credit',
    'profiles',
    'audit',
    'tasks',
    'lender',
    'sales',
    "consumers",

    # third party
    'django_celery_beat',
    'widget_tweaks',
    'easy_thumbnails',
    'image_cropping',
    'storages',
]



THUMBNAIL_ALIASES = {"": {"logo": {"size": (400, 200), "crop": True}}}

# ---------------------------
# MIDDLEWARE
# ---------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise should come right after SecurityMiddleware for static serving
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "seshibo_site.middleware.LastSeenMiddleware",
]

# Online window minutes (used by is_online)
ONLINE_WINDOW_MINUTES = 5

ROOT_URLCONF = 'seshibo_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],  # consider adding your templates folder
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'seshibo_site.wsgi.application'

# ---------------------------
# DATABASE
# ---------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv("MYSQL_DB", "dailymarket"),
        'USER': os.getenv("MYSQL_USER", "victor"),
        'PASSWORD': os.getenv("MYSQL_PASSWORD", "Enter19932021"),
        'HOST': os.getenv("MYSQL_HOST", "dailymarket.cfiwucmesuhh.eu-north-1.rds.amazonaws.com"),
        'PORT': os.getenv("MYSQL_PORT", "3306"),
        # optional: enforce utf8mb4
        'OPTIONS': {
            'charset': 'utf8mb4',
            'use_unicode': True,
        },
    }
}

# ---------------------------
# AUTH PASSWORD VALIDATORS
# ---------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]

# ---------------------------
# INTERNATIONALIZATION
# ---------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = "Africa/Johannesburg"
USE_I18N = True
USE_TZ = True

# ---------------------------
# CELERY (Optional)
# ---------------------------
CELERY_TIMEZONE = "Africa/Johannesburg"
CELERY_ENABLE_UTC = False
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL")  # e.g., redis://:password@host:6379/0
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND")

CELERY_BEAT_SCHEDULE = {
    "flag-overdue-invoices-04h45": {
        "task": "invoices.tasks.flag_overdue_invoices",
        "schedule": crontab(minute=45, hour=4),
        "options": {"queue": "default"},
    },
    "email-overdue-summary-05h00": {
        "task": "invoices.tasks.email_overdue_summary",
        "schedule": crontab(minute=0, hour=5),
        "options": {"queue": "default"},
    },
}

# ---------------------------
# EMAIL
# ---------------------------
EMAIL_HOST = os.getenv("EMAIL_HOST", "mail.thedailymarket.co.za")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", 587))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True") == "True"
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "accounts@thedailymarket.co.za")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")

DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "The Daily Market <accounts@thedailymarket.co.za>")
SUPPORT_FROM_EMAIL = os.getenv("SUPPORT_FROM_EMAIL", "The Daily Market Support <support@thedailymarket.co.za>")
SUPPORT_EMAIL = os.getenv("SUPPORT_EMAIL", "support@thedailymarket.co.za")

# ---------------------------
# STATIC & MEDIA FILES
# ---------------------------
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']  # your local static sources
STATIC_ROOT = BASE_DIR / "staticfiles"    # collectstatic target

# ---------------------------
# MEDIA FILES (LOCAL)
# ---------------------------
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Use WhiteNoise for static files (compressed + hashed filenames)
# Use this in production unless you choose to host static on S3/CDN
if DJANGO_ENV == "production":
    STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
else:
    STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"  # safe default for dev too







# ---------------------------
# DEFAULT AUTO FIELD
# ---------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ---------------------------
# PAYFAST
# ---------------------------
PAYFAST_USE_SANDBOX = os.getenv("PAYFAST_USE_SANDBOX", "True") == "True"

if PAYFAST_USE_SANDBOX:
    PAYFAST_PROCESS_URL = "https://sandbox.payfast.co.za/eng/process"
    PAYFAST_MERCHANT_ID = os.getenv("PAYFAST_MERCHANT_ID_SANDBOX", "10000100")
    PAYFAST_MERCHANT_KEY = os.getenv("PAYFAST_MERCHANT_KEY_SANDBOX", "46f0cd694581a")
else:
    PAYFAST_PROCESS_URL = "https://www.payfast.co.za/eng/process"
    PAYFAST_MERCHANT_ID = os.getenv("PAYFAST_MERCHANT_ID")
    PAYFAST_MERCHANT_KEY = os.getenv("PAYFAST_MERCHANT_KEY")

PAYFAST_PASSPHRASE = os.getenv("PAYFAST_PASSPHRASE", "HaPPy2025GiLmore")

# ---------------------------
# SESSIONS
# ---------------------------
SESSION_COOKIE_AGE = int(os.getenv("SESSION_COOKIE_AGE", 600))
SESSION_SAVE_EVERY_REQUEST = os.getenv("SESSION_SAVE_EVERY_REQUEST", "True") == "True"

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "DEBUG" if DEBUG else "WARNING",
    },
}