"""
Django settings for seshibo_site project.

Generated by 'django-admin startproject' using Django 5.2.6.
"""

from pathlib import Path
import os
from celery.schedules import crontab
from dotenv import load_dotenv
from decimal import Decimal


BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(dotenv_path=BASE_DIR / ".env")


# ---------------------------
# BASE DIR
# ---------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# ---------------------------
# SECRET KEY & DEBUG
# ---------------------------
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "fallback-secret-key-for-dev")
DEBUG = "True"
DJANGO_ENV = os.getenv("DJANGO_ENV", "development")  # "production" when live

ALLOWED_HOSTS = [
    "thedailymarket.co.za",
    "www.thedailymarket.co.za",
    "localhost",
    "127.0.0.1",
]

# ---------------------------
# LOGIN URLS
# ---------------------------
LOGIN_URL = "/"
LOGIN_REDIRECT_URL = "/"

# ---------------------------
# INSTALLED APPS
# ---------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    "communications.apps.CommunicationsConfig",

    # project apps
    'home',
    'staff_portal',
    'suppliers',
    'products',
    'clients',
    'orders',
    'invoices',
    'deliveries',
    'transactions',
    'credit',
    'profiles',
    'audit',
    'tasks',
    'lender',
    'sales',
    "consumers",
    "logistics",
    'core.apps.CoreConfig',
    "django_extensions",
    "payments",
    "online_payments",
    
    "membership",

    # third party
    'django_celery_beat',
    'widget_tweaks',
    'easy_thumbnails',
    'image_cropping',
    'storages',
]



THUMBNAIL_ALIASES = {"": {"logo": {"size": (400, 200), "crop": True}}}

# ---------------------------
# MIDDLEWARE
# ---------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise should come right after SecurityMiddleware for static serving
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "seshibo_site.middleware.LastSeenMiddleware",
    'seshibo_site.middleware.ShortSessionForPortalMiddleware',
]

# Online window minutes (used by is_online)
ONLINE_WINDOW_MINUTES = 5

ROOT_URLCONF = 'seshibo_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],  # consider adding your templates folder
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                "core.context_processors.platform_access",
                "core.context_processors.access_flags",
                "tasks.context_processors.notification_context",
            ],
        },
    },
]

WSGI_APPLICATION = 'seshibo_site.wsgi.application'

DATABASE_ROUTERS = ['seshibo_site.db_router.MultiDBRouter']

# ---------------------------
# DATABASE
# ---------------------------
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "thedail3_daily_market",
        "USER": "thedail3_daily_market",
        "PASSWORD": "Enter19931993",
        "HOST": "102.130.123.35",
        "PORT": "3306",
        "OPTIONS": {
            "charset": "utf8mb4",
        },
    },

    "dummy": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "thedail3_daily_market_dummy",
        "USER": "thedail3_daily_market",
        "PASSWORD": "Enter19931993",
        "HOST": "102.130.123.35",
        "PORT": "3306",
        "OPTIONS": {
            "charset": "utf8mb4",
        },
    },
}



# ---------------------------
# AUTH PASSWORD VALIDATORS
# ---------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]

# ---------------------------
# INTERNATIONALIZATION
# ---------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = "Africa/Johannesburg"
USE_I18N = True
USE_TZ = True

# ---------------------------
# CELERY (Optional)
# ---------------------------
CELERY_TIMEZONE = "Africa/Johannesburg"
CELERY_ENABLE_UTC = False
CELERY_BROKER_URL = "redis://localhost:6379/0"
CELERY_RESULT_BACKEND = "redis://localhost:6379/0"

CELERY_BEAT_SCHEDULE = {
    # =========================================================
    # INVOICE TASKS
    # =========================================================

    "flag-overdue-invoices-04h45": {
        "task": "invoices.tasks.flag_overdue_invoices",
        "schedule": crontab(minute=45, hour=4),
        "options": {"queue": "default"},
    },

    "email-overdue-summary-05h00": {
        "task": "invoices.tasks.email_overdue_summary",
        "schedule": crontab(minute=0, hour=5),
        "options": {"queue": "default"},
    },

    # =========================================================
    # DAILY SALES REPORTS
    # =========================================================

    "daily-supervisor-sales-reports-18h00": {
        "task": "tasks.tasks.send_daily_supervisor_sales_reports",
        "schedule": crontab(minute=0, hour=18),
        "options": {"queue": "default"},
    },

    "daily-rep-sales-reports-18h00": {
        "task": "tasks.tasks.send_daily_rep_sales_reports",
        "schedule": crontab(minute=0, hour=18),
        "options": {"queue": "default"},
    },
}



# EMAIL — Postmark API
EMAIL_BACKEND = "postmarker.django.EmailBackend"

POSTMARK = {
    "TOKEN": os.getenv("POSTMARK_TOKEN", "1a973320-7401-41f4-9747-129c404b6899"), 
}
INFO_EMAIL = os.getenv("INFO_EMAIL", "info@thedailymarket.co.za")
DEFAULT_FROM_EMAIL = "The Daily Market <accounts@thedailymarket.co.za>"
SERVER_EMAIL = DEFAULT_FROM_EMAIL

SUPPORT_EMAIL = os.getenv("SUPPORT_EMAIL", "support@thedailymarket.co.za")



# ---------------------------


# ---------------------------
# STATIC & MEDIA FILES
# ---------------------------
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']  # your local static sources
STATIC_ROOT = BASE_DIR / "staticfiles"    # collectstatic target

# ---------------------------
# MEDIA FILES (LOCAL)
# ---------------------------
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Use WhiteNoise for static files (compressed + hashed filenames)
# Use this in production unless you choose to host static on S3/CDN
if DJANGO_ENV == "production":
    STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
else:
    STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"  # safe default for dev too







# ---------------------------
# DEFAULT AUTO FIELD
# ---------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ---------------------------
# PAYFAST
# ---------------------------
PAYFAST_MERCHANT_ID = "32012381"
PAYFAST_MERCHANT_KEY = "zb8wl3tesqdck"
PAYFAST_PASSPHRASE = "HaPPy2025GiLmore"
PAYFAST_PROCESS_URL = "https://www.payfast.co.za/eng/process"


# ---------------------------
# SESSIONS
# ---------------------------
SESSION_COOKIE_AGE = int(os.getenv("SESSION_COOKIE_AGE", 600))
SESSION_SAVE_EVERY_REQUEST = os.getenv("SESSION_SAVE_EVERY_REQUEST", "True") == "True"

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "DEBUG" if DEBUG else "WARNING",
    },
}

GOOGLE_MAPS_API_KEY = "AIzaSyChVDl--ftGbLBj4zzmNf9GKcqEh_ZM9IU"

VAT_ENABLED = False
DEFAULT_VAT_PERCENT = Decimal("0.00")

# ===============================
# YOCO PAYMENT GATEWAY SETTINGS
# ===============================

# API Keys
YOCO_PUBLIC_KEY = "pk_test_c768e9b80qgDbWj0e8c4"
YOCO_SECRET_KEY = "sk_test_6486f73eOgzA6o434d747319ea9a"

# API Endpoint
YOCO_API_URL = "https://payments.yoco.com/api/checkouts"

# Default Redirect URLs
# (These can be overridden dynamically per invoice)
YOCO_SUCCESS_URL = "https://www.thedailymarket.co.za/payment-success/"
YOCO_CANCEL_URL = "https://www.thedailymarket.co.za/payment-cancel/"

# Webhook URL (Yoco sends payment confirmations here)
YOCO_WEBHOOK_URL = "https://www.thedailymarket.co.za/payments/yoco/webhook/"

YOCO_WEBHOOK_SECRET = "whsec_MDZGN0I0NUQwQTUzNDc2QTM2Qzg0QTVDMDAwQTA2MDc="


OZOW_SITE_CODE = "PER-PER-030"
OZOW_PRIVATE_KEY = "174c37e9f54a6f4c3dd906ef69cf41d2"
OZOW_API_KEY = "faad04c558849b3d2be2a3b799bf6319"

OZOW_COUNTRY_CODE = "ZA"
OZOW_CURRENCY_CODE = "ZAR"

OZOW_PAYMENT_URL = "https://pay.ozow.com"

OZOW_IS_TEST = False

OZOW_CANCEL_URL = "https://www.thedailymarket.co.za/payment/cancel/"
OZOW_ERROR_URL = "https://www.thedailymarket.co.za/payment/error/"
OZOW_SUCCESS_URL = "https://www.thedailymarket.co.za/payment/success/"
OZOW_NOTIFY_URL = "https://www.thedailymarket.co.za/payments/ozow/notify/"

OZOW_API_URL = "https://stagingapi.ozow.com" if OZOW_IS_TEST else "https://api.ozow.com"

# ===============================
# OZOW ONEAPI SETTINGS
# ===============================

OZOW_ONEAPI_USE_STAGING = False

OZOW_ONEAPI_BASE_URL = (
    "https://stagingone.ozow.com"
    if OZOW_ONEAPI_USE_STAGING
    else "https://one.ozow.com"
)

OZOW_ONEAPI_TOKEN_URL = f"{OZOW_ONEAPI_BASE_URL}/v1/token"

OZOW_ONEAPI_CLIENT_ID = "2vgnd4bjen9iesohut8487emmr"
OZOW_ONEAPI_CLIENT_SECRET = "1vnogvdskharfkeseg0rujqr1m0npfiho6sdclqbvrpvlq10l89"
OZOW_ONEAPI_SCOPE = "payments webhooks refunds"

OZOW_ONEAPI_SITE_CODE = OZOW_SITE_CODE
OZOW_ONEAPI_REGION = "ZA"
OZOW_ONEAPI_CURRENCY = "ZAR"

OZOW_ONEAPI_RETURN_URL = "https://www.thedailymarket.co.za/payments/oneapi/return/"
OZOW_ONEAPI_NOTIFY_URL = "https://www.thedailymarket.co.za/payments/oneapi/webhook/"

# 30 minute expiry window for payment links
OZOW_ONEAPI_EXPIRE_MINUTES = 30

# Optional for later webhook verification hardening
OZOW_ONEAPI_WEBHOOK_ID = ""
OZOW_ONEAPI_WEBHOOK_SECRET = ""


WHATSAPP_ACCESS_TOKEN= "EAAjsvUGFTt4BRYlAM9veBtGdYCHsM5GqsongM1DtNJOytTNKsZCb6x2gdAkTKlVY8EqBKMylM5YZBQkRv6sLuxrQUZBdv7lHjvNcF8cUscVB8ZB4K5g1pNDCJyXBA1UFjEx1UsZBXUuNMM0FZBJcjZBe3z94y1rwqZBo93yZCHheaFz2oZCFJiYP78ZA3aKip9MBwZDZD"
WHATSAPP_PHONE_NUMBER_ID= "1222113914314308"
SITE_URL = "https://www.thedailymarket.co.za"
WHATSAPP_VERIFY_TOKEN = "TheDailyMarketWebhook2026"


SMSPORTAL_CLIENT_ID = "dailymarket_api"

SMSPORTAL_API_SECRET = "TDM_SMS_2026!SecureAPI"

SITE_URL = "http://thedailymarket.co.za"

# ============================================================
# TWILIO WHATSAPP - TEST / SANDBOX
# ============================================================

TWILIO_ACCOUNT_SID = os.getenv("TWILIO_ACCOUNT_SID", "")
TWILIO_AUTH_TOKEN = os.getenv("TWILIO_AUTH_TOKEN", "")
TWILIO_WHATSAPP_FROM = os.getenv("TWILIO_WHATSAPP_FROM", "")