# Generated by Django 5.2.6 on 2026-01-18 22:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Primary name (business or person).', max_length=160)),
                ('organization', models.CharField(blank=True, help_text='Trading name if different.', max_length=200)),
                ('contact_name', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('whatsapp', models.CharField(blank=True, max_length=50)),
                ('potential_client_type', models.CharField(blank=True, choices=[('RESTAURANT', 'Restaurant'), ('CATERER', 'Caterer'), ('RETAIL', 'Retail / Supermarket / Spaza'), ('VENDOR', 'Vendor / Street Food'), ('SCHOOL', 'School / Hostel / Institution'), ('STOKVEL', 'Stokvel / Group'), ('EVENT', 'Once-off Event / Private (Funeral, Wedding, etc.)'), ('OTHER', 'Other (Specify in notes)')], help_text='What type of client you expect this to be (e.g. Restaurant, Caterer).', max_length=20)),
                ('potential_size_tier', models.CharField(blank=True, choices=[('A', 'Tier A (Large / High Volume)'), ('B', 'Tier B (Medium Volume)'), ('C', 'Tier C (Small / Low Volume)')], help_text='Expected size tier: A = large, B = medium, C = small.', max_length=1)),
                ('suburb', models.CharField(blank=True, max_length=120)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('province', models.CharField(blank=True, choices=[('EC', 'Eastern Cape'), ('FS', 'Free State'), ('GP', 'Gauteng'), ('KZN', 'KwaZulu-Natal'), ('LP', 'Limpopo'), ('MP', 'Mpumalanga'), ('NC', 'Northern Cape'), ('NW', 'North West'), ('WC', 'Western Cape')], max_length=10)),
                ('stage', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('SITE_VISIT', 'Site visit'), ('NEGOTIATION', 'Negotiation'), ('WON', 'Won'), ('LOST', 'Lost')], db_index=True, default='NEW', help_text='Where this prospect is in the sales pipeline.', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], db_index=True, default='ACTIVE', max_length=10)),
                ('estimated_weekly_spend', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated weekly spend if they become a client (Rands).', max_digits=12, null=True)),
                ('last_contact_at', models.DateTimeField(blank=True, help_text='Last time we engaged this prospect (call, visit, WhatsApp, etc.).', null=True)),
                ('next_follow_up_at', models.DateTimeField(blank=True, help_text='Planned next follow-up time.', null=True)),
                ('lead_source', models.CharField(blank=True, help_text='Where this lead came from (e.g. Facebook, referral, walk-in).', max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProspectUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('CALL', 'Call'), ('WHATSAPP', 'WhatsApp'), ('VISIT', 'Visit'), ('EMAIL', 'Email'), ('SAMPLE', 'Sample delivered / site visit'), ('NEGOTIATION', 'Negotiation / deal discussion'), ('OTHER', 'Other')], help_text='Type of activity (call, WhatsApp, visit, sample, etc.).', max_length=20)),
                ('outcome', models.CharField(blank=True, choices=[('NO_ANSWER', 'No answer'), ('ANSWERED', 'Answered'), ('INTERESTED', 'Interested'), ('NOT_INTERESTED', 'Not interested'), ('REQUESTED_PRICELIST', 'Requested price list'), ('REQUESTED_SAMPLE', 'Requested sample'), ('SAMPLE_DROPPED', 'Sample dropped off'), ('FOLLOW_UP_AGREED', 'Follow-up agreed'), ('DEAL_WON', 'Deal won'), ('DEAL_LOST', 'Deal lost'), ('OTHER', 'Other')], help_text='Outcome of this action (answered, no answer, interested, etc.).', max_length=30)),
                ('action_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this action took place.')),
                ('old_stage', models.CharField(blank=True, choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('SITE_VISIT', 'Site visit'), ('NEGOTIATION', 'Negotiation'), ('WON', 'Won'), ('LOST', 'Lost')], max_length=20)),
                ('new_stage', models.CharField(blank=True, choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('SITE_VISIT', 'Site visit'), ('NEGOTIATION', 'Negotiation'), ('WON', 'Won'), ('LOST', 'Lost')], max_length=20)),
                ('notes', models.TextField(blank=True, help_text="Extra detail (e.g. 'Called at 10:30, rang out' or 'Dropped 2kg wings').")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visit_date', models.DateField(blank=True, null=True)),
                ('visit_time_arrived', models.TimeField(blank=True, null=True)),
                ('visit_time_left', models.TimeField(blank=True, null=True)),
                ('visit_contact_name', models.CharField(blank=True, max_length=120)),
                ('visit_photo', models.ImageField(blank=True, null=True, upload_to='prospects/site_visits/')),
                ('negotiation_products', models.TextField(blank=True, help_text='What products they are interested in (now).')),
                ('negotiation_menu_opportunities', models.TextField(blank=True, help_text='Other menu items / future opportunities to target later.')),
                ('negotiation_competitor_info', models.TextField(blank=True, help_text='Current supplier, approximate pricing, or deal constraints (optional).')),
            ],
            options={
                'ordering': ['-action_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Primary display name (person or business).', max_length=160)),
                ('organization', models.CharField(blank=True, help_text='Company / Trading name (if applicable).', max_length=200)),
                ('client_type', models.CharField(choices=[('RESTAURANT', 'Restaurant'), ('CATERER', 'Caterer'), ('RETAIL', 'Retail / Supermarket / Spaza'), ('VENDOR', 'Vendor / Street Food'), ('SCHOOL', 'School / Hostel / Institution'), ('STOKVEL', 'Stokvel / Group'), ('EVENT', 'Once-off Event / Private (Funeral, Wedding, etc.)'), ('OTHER', 'Other (Specify in notes)')], default='RESTAURANT', max_length=20)),
                ('client_size_tier', models.CharField(blank=True, choices=[('A', 'Tier A (Large / High Volume)'), ('B', 'Tier B (Medium Volume)'), ('C', 'Tier C (Small / Low Volume)')], help_text='Size tier for this client: A = large, B = medium, C = small.', max_length=1)),
                ('client_number', models.CharField(db_index=True, editable=False, help_text='Auto-generated client number (e.g., CL0001).', max_length=10, unique=True)),
                ('contact_person', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('whatsapp', models.CharField(blank=True, max_length=50)),
                ('address_line1', models.CharField(blank=True, max_length=200)),
                ('address_line2', models.CharField(blank=True, max_length=200)),
                ('suburb', models.CharField(blank=True, max_length=120)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('province', models.CharField(blank=True, choices=[('EC', 'Eastern Cape'), ('FS', 'Free State'), ('GP', 'Gauteng'), ('KZN', 'KwaZulu-Natal'), ('LP', 'Limpopo'), ('MP', 'Mpumalanga'), ('NC', 'Northern Cape'), ('NW', 'North West'), ('WC', 'Western Cape')], max_length=10)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(default='South Africa', max_length=120)),
                ('delivery_address_line1', models.CharField(blank=True, max_length=255)),
                ('delivery_address_line2', models.CharField(blank=True, max_length=255)),
                ('delivery_suburb', models.CharField(blank=True, max_length=120)),
                ('delivery_city', models.CharField(blank=True, max_length=120)),
                ('delivery_province', models.CharField(blank=True, max_length=120)),
                ('delivery_postal_code', models.CharField(blank=True, max_length=20)),
                ('delivery_country', models.CharField(blank=True, default='South Africa', max_length=120)),
                ('delivery_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))])),
                ('delivery_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))])),
                ('vat_number', models.CharField(blank=True, max_length=80)),
                ('company_reg_number', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='PENDING', max_length=10)),
                ('estimated_weekly_spend', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated weekly spend in Rands (e.g., 2500.00).', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('notes', models.TextField(blank=True)),
                ('price_type', models.CharField(blank=True, choices=[('Retail', 'Retail'), ('Wholesale', 'Wholesale')], max_length=10)),
                ('last_order_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_type', models.CharField(choices=[('CASH', 'Normal (Cash/EFT)'), ('CREDIT', 'Credit Account')], default='CASH', max_length=10)),
                ('credit_status', models.CharField(choices=[('INACTIVE', 'Inactive'), ('PENDING', 'Pending'), ('ACTIVE', 'Active')], default='INACTIVE', max_length=10)),
                ('account_manager', models.ForeignKey(blank=True, help_text='Internal staff member managing this client.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
