# Generated by Django 5.2.6 on 2025-09-14 10:23

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0004_product_productpricing_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Primary display name (person or business).', max_length=160)),
                ('organization', models.CharField(blank=True, help_text='Company / Trading name (if applicable).', max_length=200)),
                ('client_type', models.CharField(choices=[('HOUSEHOLD', 'Household'), ('RESTAURANT', 'Restaurant'), ('RESELLER', 'Reseller / Spaza / Tuckshop'), ('CATERER', 'Caterer'), ('STOKVEL', 'Stokvel'), ('OTHER', 'Other')], default='HOUSEHOLD', max_length=20)),
                ('client_number', models.CharField(db_index=True, editable=False, help_text='Auto-generated client number (e.g., CL0001).', max_length=10, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('whatsapp', models.CharField(blank=True, max_length=50)),
                ('address_line1', models.CharField(blank=True, max_length=200)),
                ('address_line2', models.CharField(blank=True, max_length=200)),
                ('suburb', models.CharField(blank=True, max_length=120)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('province', models.CharField(blank=True, choices=[('EC', 'Eastern Cape'), ('FS', 'Free State'), ('GP', 'Gauteng'), ('KZN', 'KwaZulu-Natal'), ('LP', 'Limpopo'), ('MP', 'Mpumalanga'), ('NC', 'Northern Cape'), ('NW', 'North West'), ('WC', 'Western Cape')], max_length=10)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(default='South Africa', max_length=120)),
                ('vat_number', models.CharField(blank=True, max_length=80)),
                ('company_reg_number', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='PENDING', max_length=10)),
                ('estimated_weekly_spend', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated weekly spend in Rands (e.g., 2500.00).', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('notes', models.TextField(blank=True)),
                ('last_order_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_manager', models.ForeignKey(blank=True, help_text='Internal staff member managing this client.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_clients', to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(blank=True, help_text='What product categories this client typically buys.', related_name='clients', to='products.category')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='clients_cli_name_5ab7bc_idx'), models.Index(fields=['client_type'], name='clients_cli_client__1e0f73_idx'), models.Index(fields=['status'], name='clients_cli_status_ce0d15_idx'), models.Index(fields=['client_number'], name='clients_cli_client__d84143_idx')],
                'unique_together': {('name', 'organization')},
            },
        ),
    ]
