# Generated by Django 5.2.6 on 2026-01-18 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('credit', '0002_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='What product categories this client typically buys.', related_name='clients', to='products.category'),
        ),
        migrations.AddField(
            model_name='client',
            name='funder',
            field=models.ForeignKey(blank=True, help_text="Optional: which funder backs this client's credit.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='credit.funder'),
        ),
        migrations.AddField(
            model_name='prospect',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Client created from this prospect (if converted).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospects', to='clients.client'),
        ),
        migrations.AddField(
            model_name='prospect',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Who originally created this prospect.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospects_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prospect',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Sales rep responsible for this prospect.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prospectupdate',
            name='prospect',
            field=models.ForeignKey(help_text='Prospect this update belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='clients.prospect'),
        ),
        migrations.AddField(
            model_name='prospectupdate',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Who logged/performed this action.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospect_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['name'], name='clients_cli_name_5ab7bc_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['client_type'], name='clients_cli_client__1e0f73_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['status'], name='clients_cli_status_ce0d15_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['client_number'], name='clients_cli_client__d84143_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['client_type', 'client_size_tier'], name='clients_cli_client__e8e2cf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('name', 'organization')},
        ),
        migrations.AddIndex(
            model_name='prospect',
            index=models.Index(fields=['stage'], name='clients_pro_stage_a6dea5_idx'),
        ),
        migrations.AddIndex(
            model_name='prospect',
            index=models.Index(fields=['status'], name='clients_pro_status_c047b2_idx'),
        ),
        migrations.AddIndex(
            model_name='prospect',
            index=models.Index(fields=['owner', 'stage'], name='clients_pro_owner_i_25893e_idx'),
        ),
        migrations.AddIndex(
            model_name='prospect',
            index=models.Index(fields=['city', 'province'], name='clients_pro_city_8bd134_idx'),
        ),
        migrations.AddIndex(
            model_name='prospect',
            index=models.Index(fields=['created_by', 'created_at'], name='clients_pro_created_29e24e_idx'),
        ),
        migrations.AddIndex(
            model_name='prospectupdate',
            index=models.Index(fields=['prospect', 'action_at'], name='clients_pro_prospec_5e98da_idx'),
        ),
        migrations.AddIndex(
            model_name='prospectupdate',
            index=models.Index(fields=['action_type'], name='clients_pro_action__b73228_idx'),
        ),
        migrations.AddIndex(
            model_name='prospectupdate',
            index=models.Index(fields=['outcome'], name='clients_pro_outcome_ea12e3_idx'),
        ),
    ]
