# Generated by Django 5.2.6 on 2025-09-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_contact_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='credit_status',
            field=models.CharField(choices=[('inactive', 'Inactive'), ('pending', 'Pending'), ('active', 'Active')], default='inactive', max_length=10),
        ),
    ]
