# Generated by Django 5.2.6 on 2025-09-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_credit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='account_type',
            field=models.CharField(choices=[('CASH', 'Normal (Cash/EFT)'), ('CREDIT', 'Credit Account')], default='CASH', max_length=10),
        ),
        migrations.AlterField(
            model_name='client',
            name='credit_status',
            field=models.CharField(choices=[('INACTIVE', 'Inactive'), ('PENDING', 'Pending'), ('ACTIVE', 'Active')], default='INACTIVE', max_length=10),
        ),
    ]
