# Generated by Django 5.2.6 on 2026-01-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_clientcompliance_clientcompliancedocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='delivery_province',
            field=models.CharField(blank=True, choices=[('EC', 'Eastern Cape'), ('FS', 'Free State'), ('GP', 'Gauteng'), ('KZN', 'KwaZulu-Natal'), ('LP', 'Limpopo'), ('MP', 'Mpumalanga'), ('NC', 'Northern Cape'), ('NW', 'North West'), ('WC', 'Western Cape')], max_length=10),
        ),
    ]
