# Generated by Django 5.2.6 on 2025-09-28 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_client_delivery_address_line1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='price_type',
            field=models.CharField(blank=True, choices=[('Retail', 'Retail'), ('Wholesale', 'Wholesale')], max_length=10),
        ),
    ]
