# Generated by Django 5.2.6 on 2026-01-26 12:10

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_remove_clientcompliancedocument_is_verified_and_more'),
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='address_line1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='prospect',
            name='address_line2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='prospect',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='What this prospect is likely to buy.', related_name='prospects', to='products.category'),
        ),
        migrations.AddField(
            model_name='prospect',
            name='company_reg_number',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='prospect',
            name='country',
            field=models.CharField(default='South Africa', max_length=120),
        ),
        migrations.AddField(
            model_name='prospect',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='prospect',
            name='vat_number',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='estimated_weekly_spend',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated weekly spend if converted (Rands).', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='last_contact_at',
            field=models.DateTimeField(blank=True, help_text='Last engagement with this prospect.', null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='lead_source',
            field=models.CharField(blank=True, help_text='Where this lead came from (referral, walk-in, Facebook, etc.).', max_length=120),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='next_follow_up_at',
            field=models.DateTimeField(blank=True, help_text='Planned next follow-up.', null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='potential_client_type',
            field=models.CharField(blank=True, choices=[('RESTAURANT', 'Restaurant'), ('CATERER', 'Caterer'), ('RETAIL', 'Retail / Supermarket / Spaza'), ('VENDOR', 'Vendor / Street Food'), ('SCHOOL', 'School / Hostel / Institution'), ('STOKVEL', 'Stokvel / Group'), ('EVENT', 'Once-off Event / Private (Funeral, Wedding, etc.)'), ('OTHER', 'Other (Specify in notes)')], help_text='Expected client type (e.g. Restaurant, Caterer).', max_length=20),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='potential_size_tier',
            field=models.CharField(blank=True, choices=[('A', 'Tier A (Large / High Volume)'), ('B', 'Tier B (Medium Volume)'), ('C', 'Tier C (Small / Low Volume)')], help_text='Expected size tier: A (large), B (medium), C (small).', max_length=1),
        ),
    ]
