# Generated by Django 5.2.6 on 2025-11-09 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_client_price_type'),
        ('credit', '0005_funder_funderclientweek_fundermovement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='funder',
            field=models.ForeignKey(blank=True, help_text="Optional: which funder backs this client's credit.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='credit.funder'),
        ),
    ]
