# Generated by Django 5.2.6 on 2026-01-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_prospect_address_line1_prospect_address_line2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='city',
            field=models.CharField(blank=True, choices=[('Johannesburg', 'Johannesburg'), ('Pretoria', 'Pretoria'), ('Centurion', 'Centurion'), ('Midrand', 'Midrand'), ('Sandton', 'Sandton'), ('Randburg', 'Randburg'), ('Roodepoort', 'Roodepoort'), ('Soweto', 'Soweto'), ('Alberton', 'Alberton'), ('Benoni', 'Benoni'), ('Boksburg', 'Boksburg'), ('Brakpan', 'Brakpan'), ('Edenvale', 'Edenvale'), ('Germiston', 'Germiston'), ('Kempton Park', 'Kempton Park'), ('Nigel', 'Nigel'), ('Springs', 'Springs'), ('Krugersdorp', 'Krugersdorp'), ('Randfontein', 'Randfontein'), ('Westonaria', 'Westonaria'), ('Carletonville', 'Carletonville'), ('Akasia', 'Akasia'), ('Atteridgeville', 'Atteridgeville'), ('Mamelodi', 'Mamelodi'), ('Soshanguve', 'Soshanguve'), ('Ga-Rankuwa', 'Ga-Rankuwa'), ('Bedfordview', 'Bedfordview'), ('Fourways', 'Fourways'), ('Bryanston', 'Bryanston'), ('Rosebank', 'Rosebank'), ('Melville', 'Melville'), ('Florida', 'Florida'), ('Lenasia', 'Lenasia'), ('Tembisa', 'Tembisa'), ('Daveyton', 'Daveyton'), ('Katlehong', 'Katlehong'), ('Vosloorus', 'Vosloorus'), ('Thokoza', 'Thokoza'), ('Tsakane', 'Tsakane'), ('Kwa-Thema', 'Kwa-Thema'), ('Other (Gauteng)', 'Other (Gauteng)')], max_length=120),
        ),
    ]
