# Generated by Django 5.2.6 on 2025-11-16 20:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_client_funder'),
        ('credit', '0008_fundermember'),
        ('products', '0011_productpricing_skip_variant_sync'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_size_tier',
            field=models.CharField(blank=True, choices=[('A', 'Tier A (Large / High Volume)'), ('B', 'Tier B (Medium Volume)'), ('C', 'Tier C (Small / Low Volume)')], help_text='Size tier for this client: A = large, B = medium, C = small.', max_length=1),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('HOUSEHOLD', 'Household'), ('RESTAURANT', 'Restaurant'), ('CATERER', 'Caterer'), ('RETAIL', 'Retail / Supermarket / Spaza'), ('VENDOR', 'Vendor / Street Food'), ('SCHOOL', 'School / Hostel / Institution'), ('STOKVEL', 'Stokvel / Group'), ('EVENT', 'Once-off Event / Private (Funeral, Wedding, etc.)'), ('OTHER', 'Other (Specify in notes)')], default='HOUSEHOLD', max_length=20),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['client_type', 'client_size_tier'], name='clients_cli_client__e8e2cf_idx'),
        ),
    ]
