# Generated by Django 5.2.6 on 2025-11-17 07:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_client_client_size_tier_alter_client_client_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('RESTAURANT', 'Restaurant'), ('CATERER', 'Caterer'), ('RETAIL', 'Retail / Supermarket / Spaza'), ('VENDOR', 'Vendor / Street Food'), ('SCHOOL', 'School / Hostel / Institution'), ('STOKVEL', 'Stokvel / Group'), ('EVENT', 'Once-off Event / Private (Funeral, Wedding, etc.)'), ('OTHER', 'Other (Specify in notes)')], default='RESTAURANT', max_length=20),
        ),
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Primary name (business or person).', max_length=160)),
                ('organization', models.CharField(blank=True, help_text='Trading name if different.', max_length=200)),
                ('contact_name', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('whatsapp', models.CharField(blank=True, max_length=50)),
                ('potential_client_type', models.CharField(blank=True, choices=[('RESTAURANT', 'Restaurant'), ('CATERER', 'Caterer'), ('RETAIL', 'Retail / Supermarket / Spaza'), ('VENDOR', 'Vendor / Street Food'), ('SCHOOL', 'School / Hostel / Institution'), ('STOKVEL', 'Stokvel / Group'), ('EVENT', 'Once-off Event / Private (Funeral, Wedding, etc.)'), ('OTHER', 'Other (Specify in notes)')], help_text='What type of client you expect this to be (e.g. Restaurant, Caterer).', max_length=20)),
                ('potential_size_tier', models.CharField(blank=True, choices=[('A', 'Tier A (Large / High Volume)'), ('B', 'Tier B (Medium Volume)'), ('C', 'Tier C (Small / Low Volume)')], help_text='Expected size tier: A = large, B = medium, C = small.', max_length=1)),
                ('suburb', models.CharField(blank=True, max_length=120)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('province', models.CharField(blank=True, choices=[('EC', 'Eastern Cape'), ('FS', 'Free State'), ('GP', 'Gauteng'), ('KZN', 'KwaZulu-Natal'), ('LP', 'Limpopo'), ('MP', 'Mpumalanga'), ('NC', 'Northern Cape'), ('NW', 'North West'), ('WC', 'Western Cape')], max_length=10)),
                ('stage', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('SAMPLES_GIVEN', 'Samples given'), ('NEGOTIATION', 'Negotiation'), ('WON', 'Won'), ('LOST', 'Lost')], db_index=True, default='NEW', help_text='Where this prospect is in the sales pipeline.', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], db_index=True, default='ACTIVE', max_length=10)),
                ('estimated_weekly_spend', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated weekly spend if they become a client (Rands).', max_digits=12, null=True)),
                ('last_contact_at', models.DateTimeField(blank=True, help_text='Last time we engaged this prospect (call, visit, WhatsApp, etc.).', null=True)),
                ('next_follow_up_at', models.DateTimeField(blank=True, help_text='Planned next follow-up time.', null=True)),
                ('lead_source', models.CharField(blank=True, help_text='Where this lead came from (e.g. Facebook, referral, walk-in).', max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, help_text='Client created from this prospect (if converted).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospects', to='clients.client')),
                ('owner', models.ForeignKey(blank=True, help_text='Sales rep responsible for this prospect.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProspectUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('CALL', 'Call'), ('WHATSAPP', 'WhatsApp'), ('VISIT', 'Visit'), ('EMAIL', 'Email'), ('SAMPLE', 'Sample delivered'), ('OTHER', 'Other')], help_text='Type of activity (call, WhatsApp, visit, sample, etc.).', max_length=20)),
                ('outcome', models.CharField(blank=True, choices=[('NO_ANSWER', 'No answer'), ('ANSWERED', 'Answered'), ('INTERESTED', 'Interested'), ('NOT_INTERESTED', 'Not interested'), ('REQUESTED_PRICELIST', 'Requested price list'), ('REQUESTED_SAMPLE', 'Requested sample'), ('SAMPLE_DROPPED', 'Sample dropped off'), ('FOLLOW_UP_AGREED', 'Follow-up agreed'), ('DEAL_WON', 'Deal won'), ('DEAL_LOST', 'Deal lost'), ('OTHER', 'Other')], help_text='Outcome of this action (answered, no answer, interested, etc.).', max_length=30)),
                ('action_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this action took place.')),
                ('old_stage', models.CharField(blank=True, choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('SAMPLES_GIVEN', 'Samples given'), ('NEGOTIATION', 'Negotiation'), ('WON', 'Won'), ('LOST', 'Lost')], max_length=20)),
                ('new_stage', models.CharField(blank=True, choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('SAMPLES_GIVEN', 'Samples given'), ('NEGOTIATION', 'Negotiation'), ('WON', 'Won'), ('LOST', 'Lost')], max_length=20)),
                ('notes', models.TextField(blank=True, help_text="Extra detail (e.g. 'Called at 10:30, rang out' or 'Dropped 2kg wings').")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prospect', models.ForeignKey(help_text='Prospect this update belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='clients.prospect')),
                ('user', models.ForeignKey(blank=True, help_text='Who logged/performed this action.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospect_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-action_at', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='prospect',
            index=models.Index(fields=['stage'], name='clients_pro_stage_a6dea5_idx'),
        ),
        migrations.AddIndex(
            model_name='prospect',
            index=models.Index(fields=['status'], name='clients_pro_status_c047b2_idx'),
        ),
        migrations.AddIndex(
            model_name='prospect',
            index=models.Index(fields=['owner', 'stage'], name='clients_pro_owner_i_25893e_idx'),
        ),
        migrations.AddIndex(
            model_name='prospect',
            index=models.Index(fields=['city', 'province'], name='clients_pro_city_8bd134_idx'),
        ),
        migrations.AddIndex(
            model_name='prospectupdate',
            index=models.Index(fields=['prospect', 'action_at'], name='clients_pro_prospec_5e98da_idx'),
        ),
        migrations.AddIndex(
            model_name='prospectupdate',
            index=models.Index(fields=['action_type'], name='clients_pro_action__b73228_idx'),
        ),
        migrations.AddIndex(
            model_name='prospectupdate',
            index=models.Index(fields=['outcome'], name='clients_pro_outcome_ea12e3_idx'),
        ),
    ]
