# Generated by Django 5.2.6 on 2026-02-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_alter_client_city_alter_client_delivery_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='entity_type',
            field=models.CharField(choices=[('COMPANY', 'Registered Company'), ('SOLE_TRADER', 'Sole Trader / Individual')], default='COMPANY', help_text='Whether this prospect is a registered company or a sole trader.', max_length=20),
        ),
        migrations.AddField(
            model_name='prospect',
            name='registration_identifier',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
