# Generated by Django 5.2.6 on 2025-12-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_alter_client_client_type_prospect_prospectupdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='stage',
            field=models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('SITE_VISIT', 'Site visit'), ('NEGOTIATION', 'Negotiation'), ('WON', 'Won'), ('LOST', 'Lost')], db_index=True, default='NEW', help_text='Where this prospect is in the sales pipeline.', max_length=20),
        ),
        migrations.AlterField(
            model_name='prospectupdate',
            name='new_stage',
            field=models.CharField(blank=True, choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('SITE_VISIT', 'Site visit'), ('NEGOTIATION', 'Negotiation'), ('WON', 'Won'), ('LOST', 'Lost')], max_length=20),
        ),
        migrations.AlterField(
            model_name='prospectupdate',
            name='old_stage',
            field=models.CharField(blank=True, choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('SITE_VISIT', 'Site visit'), ('NEGOTIATION', 'Negotiation'), ('WON', 'Won'), ('LOST', 'Lost')], max_length=20),
        ),
    ]
