# Generated by Django 5.2.6 on 2026-02-07 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_prospect_entity_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='entity_type',
            field=models.CharField(choices=[('COMPANY', 'Registered Company'), ('SOLE_TRADER', 'Sole Trader / Individual')], default='COMPANY', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='registration_identifier',
            field=models.CharField(blank=True, help_text='Company registration number or SA ID number.', max_length=80),
        ),
    ]
