# Generated by Django 5.2.6 on 2026-02-08 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_client_entity_type_client_registration_identifier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientcompliance',
            old_name='company_reg_number',
            new_name='registration_identifier',
        ),
        migrations.RemoveField(
            model_name='client',
            name='company_reg_number',
        ),
        migrations.RemoveField(
            model_name='prospect',
            name='company_reg_number',
        ),
    ]
