# Generated by Django 5.2.6 on 2025-12-06 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_alter_prospect_stage_alter_prospectupdate_new_stage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Who originally created this prospect.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospects_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prospectupdate',
            name='action_type',
            field=models.CharField(choices=[('CALL', 'Call'), ('WHATSAPP', 'WhatsApp'), ('VISIT', 'Visit'), ('EMAIL', 'Email'), ('SAMPLE', 'Sample delivered / site visit'), ('OTHER', 'Other')], help_text='Type of activity (call, WhatsApp, visit, sample, etc.).', max_length=20),
        ),
        migrations.AddIndex(
            model_name='prospect',
            index=models.Index(fields=['created_by', 'created_at'], name='clients_pro_created_29e24e_idx'),
        ),
    ]
