# Generated by Django 5.2.6 on 2025-12-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_prospect_created_by_alter_prospectupdate_action_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospectupdate',
            name='visit_contact_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='prospectupdate',
            name='visit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prospectupdate',
            name='visit_photo',
            field=models.ImageField(blank=True, null=True, upload_to='prospects/site_visits/'),
        ),
        migrations.AddField(
            model_name='prospectupdate',
            name='visit_time_arrived',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prospectupdate',
            name='visit_time_left',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prospectupdate',
            name='action_type',
            field=models.CharField(choices=[('CALL', 'Call'), ('WHATSAPP', 'WhatsApp'), ('VISIT', 'Visit'), ('EMAIL', 'Email'), ('SAMPLE', 'Sample delivered / site visit'), ('NEGOTIATION', 'Negotiation / deal discussion'), ('OTHER', 'Other')], help_text='Type of activity (call, WhatsApp, visit, sample, etc.).', max_length=20),
        ),
    ]
