# Generated by Django 5.2.6 on 2025-12-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_prospectupdate_visit_contact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospectupdate',
            name='negotiation_competitor_info',
            field=models.TextField(blank=True, help_text='Current supplier, approximate pricing, or deal constraints (optional).'),
        ),
        migrations.AddField(
            model_name='prospectupdate',
            name='negotiation_menu_opportunities',
            field=models.TextField(blank=True, help_text='Other menu items / future opportunities to target later.'),
        ),
        migrations.AddField(
            model_name='prospectupdate',
            name='negotiation_products',
            field=models.TextField(blank=True, help_text='What products they are interested in (now).'),
        ),
    ]
