# Generated by Django 5.2.6 on 2026-02-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_clientoperatinghours_prospectoperatinghours'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='area',
            field=models.CharField(choices=[('NORTH_CENTRAL', 'North/Central'), ('SOUTH_WEST', 'South/West'), ('EAST', 'East')], default='NORTH_CENTRAL', help_text='Territory assignment for this client.', max_length=20),
            preserve_default=False,
        ),
    ]
