# Generated by Django 5.2.6 on 2026-02-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_client_preferred_delivery_slot_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientoperatinghours',
            name='day_order',
            field=models.IntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prospectoperatinghours',
            name='day_order',
            field=models.IntegerField(default=1, editable=False),
            preserve_default=False,
        ),
    ]
