# Generated by Django 5.2.6 on 2026-02-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0015_clientoperatinghours_day_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='area',
            field=models.CharField(choices=[('NORTH_CENTRAL', 'North/Central'), ('SOUTH_WEST', 'South/West'), ('EAST', 'East')], default='NORTH_CENTRAL', help_text='Territory assignment for this prospect.', max_length=20),
            preserve_default=False,
        ),
    ]
