# Generated by Django 5.2.6 on 2026-03-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0016_prospect_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_dummy',
            field=models.BooleanField(default=False, help_text='Indicates whether this is a dummy client for funder/internal use only.'),
        ),
    ]
