# Generated by Django 5.2.6 on 2026-05-14 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0017_client_is_dummy'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='preferred_delivery_slot_1',
            field=models.CharField(blank=True, choices=[('SLOT_1', '08:00 - 10:00'), ('SLOT_2', '10:30 - 14:00'), ('SLOT_3', '14:30 - 17:00')], help_text="Prospect's first preferred delivery slot.", max_length=10),
        ),
        migrations.AddField(
            model_name='prospect',
            name='preferred_delivery_slot_2',
            field=models.CharField(blank=True, choices=[('SLOT_1', '08:00 - 10:00'), ('SLOT_2', '10:30 - 14:00'), ('SLOT_3', '14:30 - 17:00')], help_text="Prospect's second preferred delivery slot.", max_length=10),
        ),
        migrations.AddField(
            model_name='prospect',
            name='preferred_delivery_slot_3',
            field=models.CharField(blank=True, choices=[('SLOT_1', '08:00 - 10:00'), ('SLOT_2', '10:30 - 14:00'), ('SLOT_3', '14:30 - 17:00')], help_text="Prospect's third preferred delivery slot.", max_length=10),
        ),
    ]
