# Generated by Django 5.2.6 on 2026-05-27 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0018_prospect_preferred_delivery_slot_1_and_more'),
        ('profiles', '0004_salesrepprofile_base_commission_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='sales_operator',
            field=models.ForeignKey(blank=True, help_text='Sales operator responsible for this client.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='profiles.salesoperator'),
        ),
        migrations.AddField(
            model_name='prospect',
            name='sales_operator',
            field=models.ForeignKey(blank=True, help_text='Sales operator responsible for this prospect.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospects', to='profiles.salesoperator'),
        ),
        migrations.AlterField(
            model_name='client',
            name='area',
            field=models.CharField(choices=[('SOUTH_WEST', 'South / West'), ('EAST', 'East'), ('NORTH_CENTRAL', 'North / Central'), ('MIDVAAL', 'Midvaal'), ('PRETORIA', 'Pretoria'), ('OTHER', 'Other')], help_text='Territory assignment for this client.', max_length=20),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='area',
            field=models.CharField(choices=[('SOUTH_WEST', 'South / West'), ('EAST', 'East'), ('NORTH_CENTRAL', 'North / Central'), ('MIDVAAL', 'Midvaal'), ('PRETORIA', 'Pretoria'), ('OTHER', 'Other')], help_text='Territory assignment for this prospect.', max_length=20),
        ),
    ]
