# Generated by Django 5.2.6 on 2026-06-21 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0020_prospect_lat_prospect_lng'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientoperatinghours',
            options={'ordering': ['day_order']},
        ),
        migrations.AlterModelOptions(
            name='prospectoperatinghours',
            options={'ordering': ['day_order']},
        ),
    ]
