# Generated by Django 5.2.6 on 2026-06-27 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0021_alter_clientoperatinghours_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_number', models.CharField(db_index=True, editable=False, help_text='Automatically generated membership number.', max_length=20, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('source', models.CharField(choices=[('WEBSITE', 'Website'), ('SALES', 'Sales Representative'), ('ADMIN', 'Administrator'), ('IMPORT', 'Imported')], default='WEBSITE', help_text='Where this membership originated.', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True, help_text='When the membership application was submitted.')),
                ('activated_at', models.DateTimeField(blank=True, help_text='When the membership became active.', null=True)),
                ('suspended_at', models.DateTimeField(blank=True, help_text='When the membership was suspended.', null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='When the membership was cancelled.', null=True)),
                ('is_test_member', models.BooleanField(default=False, help_text='Used for testing and demonstration memberships.')),
                ('internal_notes', models.TextField(blank=True, help_text='Internal notes visible to staff only.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(help_text='The client that owns this membership.', on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='clients.client')),
            ],
            options={
                'verbose_name': 'Membership',
                'verbose_name_plural': 'Memberships',
                'ordering': ['membership_number'],
                'indexes': [models.Index(fields=['status'], name='clients_mem_status_2bbdf4_idx')],
            },
        ),
    ]
