# Generated by Django 5.2.6 on 2026-06-29 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0022_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='referral_code',
            field=models.CharField(blank=True, db_index=True, help_text='Unique referral code for this member.', max_length=20, unique=True),
        ),
    ]
