# Generated by Django 5.2.6 on 2026-06-30 02:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0023_membership_referral_code'),
        ('products', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_number', models.CharField(db_index=True, editable=False, max_length=12, unique=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('QUALIFIED', 'Qualified'), ('DISQUALIFIED', 'Disqualified'), ('CONVERTED', 'Converted to Prospect')], db_index=True, default='NEW', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('HOT', 'Hot')], default='MEDIUM', max_length=10)),
                ('source', models.CharField(choices=[('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instagram'), ('TIKTOK', 'TikTok'), ('WHATSAPP', 'WhatsApp'), ('WEBSITE', 'Website'), ('REFERRAL', 'Referral'), ('SALES_DRIVE', 'Sales Drive'), ('PHONE', 'Phone Call'), ('EMAIL', 'Email'), ('OTHER', 'Other')], db_index=True, default='WHATSAPP', max_length=20)),
                ('campaign', models.CharField(blank=True, help_text='Marketing campaign that generated this lead.', max_length=150)),
                ('advert', models.CharField(blank=True, help_text='Specific advert, video or creative.', max_length=150)),
                ('medium', models.CharField(blank=True, help_text='Example: Organic Post, QR Code, Click-to-WhatsApp.', max_length=100)),
                ('business_name', models.CharField(blank=True, max_length=200)),
                ('entity_type', models.CharField(choices=[('COMPANY', 'Registered Company'), ('SOLE_TRADER', 'Sole Trader / Individual')], default='COMPANY', max_length=20)),
                ('potential_client_type', models.CharField(blank=True, choices=[('RESTAURANT', 'Restaurant'), ('CATERER', 'Caterer'), ('RETAIL', 'Retail / Supermarket / Spaza'), ('VENDOR', 'Vendor / Street Food'), ('SCHOOL', 'School / Hostel / Institution'), ('STOKVEL', 'Stokvel / Group'), ('EVENT', 'Once-off Event / Private (Funeral, Wedding, etc.)'), ('OTHER', 'Other (Specify in notes)')], max_length=20)),
                ('estimated_weekly_spend', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('contact_person', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=50)),
                ('whatsapp', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address_line1', models.CharField(blank=True, max_length=200)),
                ('address_line2', models.CharField(blank=True, max_length=200)),
                ('suburb', models.CharField(blank=True, max_length=120)),
                ('city', models.CharField(blank=True, choices=[('Johannesburg', 'Johannesburg'), ('Pretoria', 'Pretoria'), ('Centurion', 'Centurion'), ('Midrand', 'Midrand'), ('Sandton', 'Sandton'), ('Randburg', 'Randburg'), ('Roodepoort', 'Roodepoort'), ('Soweto', 'Soweto'), ('Alberton', 'Alberton'), ('Benoni', 'Benoni'), ('Boksburg', 'Boksburg'), ('Brakpan', 'Brakpan'), ('Edenvale', 'Edenvale'), ('Germiston', 'Germiston'), ('Kempton Park', 'Kempton Park'), ('Nigel', 'Nigel'), ('Springs', 'Springs'), ('Krugersdorp', 'Krugersdorp'), ('Randfontein', 'Randfontein'), ('Westonaria', 'Westonaria'), ('Carletonville', 'Carletonville'), ('Akasia', 'Akasia'), ('Atteridgeville', 'Atteridgeville'), ('Mamelodi', 'Mamelodi'), ('Soshanguve', 'Soshanguve'), ('Ga-Rankuwa', 'Ga-Rankuwa'), ('Bedfordview', 'Bedfordview'), ('Fourways', 'Fourways'), ('Bryanston', 'Bryanston'), ('Rosebank', 'Rosebank'), ('Melville', 'Melville'), ('Florida', 'Florida'), ('Lenasia', 'Lenasia'), ('Tembisa', 'Tembisa'), ('Daveyton', 'Daveyton'), ('Katlehong', 'Katlehong'), ('Vosloorus', 'Vosloorus'), ('Thokoza', 'Thokoza'), ('Tsakane', 'Tsakane'), ('Kwa-Thema', 'Kwa-Thema'), ('Other (Gauteng)', 'Other (Gauteng)')], max_length=120)),
                ('province', models.CharField(choices=[('EC', 'Eastern Cape'), ('FS', 'Free State'), ('GP', 'Gauteng'), ('KZN', 'KwaZulu-Natal'), ('LP', 'Limpopo'), ('MP', 'Mpumalanga'), ('NC', 'Northern Cape'), ('NW', 'North West'), ('WC', 'Western Cape')], default='GP', max_length=10)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(default='South Africa', max_length=120)),
                ('area', models.CharField(blank=True, choices=[('SOUTH_WEST', 'South / West'), ('EAST', 'East'), ('NORTH_CENTRAL', 'North / Central'), ('MIDVAAL', 'Midvaal'), ('PRETORIA', 'Pretoria'), ('OTHER', 'Other')], max_length=20)),
                ('last_contact_at', models.DateTimeField(blank=True, null=True)),
                ('next_follow_up_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leads', to=settings.AUTH_USER_MODEL)),
                ('interested_in', models.ManyToManyField(blank=True, related_name='leads', to='products.category')),
                ('prospect', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead', to='clients.prospect')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='clients_lea_status_d47432_idx'), models.Index(fields=['priority'], name='clients_lea_priorit_650657_idx'), models.Index(fields=['source'], name='clients_lea_source_af432c_idx'), models.Index(fields=['assigned_to'], name='clients_lea_assigne_5dc5a8_idx'), models.Index(fields=['created_at'], name='clients_lea_created_e441f3_idx'), models.Index(fields=['city'], name='clients_lea_city_6147f4_idx'), models.Index(fields=['potential_client_type'], name='clients_lea_potenti_1f9169_idx')],
            },
        ),
    ]
