# Generated by Django 5.2.6 on 2026-06-30 06:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0024_lead'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='preferred_call_time',
            field=models.CharField(blank=True, choices=[('MORNING', '08:30 - 11:00'), ('MIDDAY', '11:00 - 14:00'), ('AFTERNOON', '14:00 - 17:30')], help_text="Customer's preferred time to receive a call.", max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='preferred_call_time_selected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('LEAD_CREATED', 'Lead Created'), ('SMS_SENT', 'SMS Sent'), ('WHATSAPP_SENT', 'WhatsApp Sent'), ('EMAIL_SENT', 'Email Sent'), ('CALLBACK_SELECTED', 'Callback Time Selected'), ('CALL_ATTEMPT', 'Call Attempt'), ('CALL_COMPLETED', 'Call Completed'), ('NO_ANSWER', 'No Answer'), ('VOICE_NOTE_SENT', 'Voice Note Sent'), ('PRICE_LIST_SENT', 'Price List Sent'), ('FOLLOW_UP_BOOKED', 'Follow-up Booked'), ('STATUS_CHANGED', 'Status Changed'), ('NOTE', 'Internal Note'), ('CONVERTED', 'Converted to Prospect')], max_length=30)),
                ('outcome', models.CharField(blank=True, choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('DELIVERED', 'Delivered'), ('READ', 'Read'), ('ANSWERED', 'Answered'), ('NO_ANSWER', 'No Answer'), ('INTERESTED', 'Interested'), ('NOT_INTERESTED', 'Not Interested'), ('OTHER', 'Other')], max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='clients.lead')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at', '-created_at'],
                'indexes': [models.Index(fields=['lead', 'occurred_at'], name='clients_lea_lead_id_e7293b_idx'), models.Index(fields=['activity_type'], name='clients_lea_activit_4827da_idx')],
            },
        ),
    ]
