# Generated by Django 5.2.6 on 2026-07-05 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0025_lead_preferred_call_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadactivity',
            name='activity_type',
            field=models.CharField(choices=[('LEAD_CREATED', 'Lead Created'), ('SMS_SENT', 'SMS Sent'), ('WHATSAPP_SENT', 'WhatsApp Sent'), ('EMAIL_SENT', 'Email Sent'), ('CALLBACK_SELECTED', 'Callback Time Selected'), ('CALL_ATTEMPT', 'Call Attempt'), ('CALL_COMPLETED', 'Call Completed'), ('NO_ANSWER', 'No Answer'), ('VOICE_NOTE_SENT', 'Voice Note Sent'), ('PRICE_LIST_SENT', 'Price List Sent'), ('FOLLOW_UP_BOOKED', 'Follow-up Booked'), ('STATUS_CHANGED', 'Status Changed'), ('NOTE', 'Internal Note'), ('CONVERTED', 'Converted to Prospect'), ('LEAD_UPDATED', 'Lead Updated')], max_length=30),
        ),
    ]
