# Generated by Django 5.2.6 on 2026-07-05 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0026_alter_leadactivity_activity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='tier',
            field=models.CharField(choices=[('BRONZE', 'Bronze'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum')], db_index=True, default='BRONZE', help_text='Current Trade Assist membership tier.', max_length=20),
        ),
        migrations.AddField(
            model_name='membership',
            name='trade_points',
            field=models.PositiveIntegerField(default=0, help_text='Current available Trade Points.'),
        ),
    ]
