# Generated by Django 5.2.6 on 2026-07-05 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0027_membership_tier_membership_trade_points'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='trade_points',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Current available Trade Points.'),
        ),
        migrations.CreateModel(
            name='TradePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], db_index=True, help_text='Whether points were credited or debited.', max_length=10)),
                ('reason', models.CharField(choices=[('WELCOME', 'Welcome Bonus'), ('INVOICE', 'Paid Invoice'), ('REFERRAL', 'Referral Bonus'), ('PROMOTION', 'Promotion'), ('REDEMPTION', 'Redemption'), ('ADJUSTMENT', 'Manual Adjustment'), ('REVERSAL', 'Reversal'), ('OTHER', 'Other')], db_index=True, help_text='Reason for this Trade Point transaction.', max_length=20)),
                ('points', models.PositiveIntegerField(help_text='Number of Trade Points moved.')),
                ('balance_after', models.PositiveIntegerField(editable=False, help_text="Member's Trade Point balance after this transaction.")),
                ('reference', models.CharField(blank=True, help_text='Optional external reference such as an invoice number.', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Optional internal notes.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this transaction. Blank if created automatically by the system.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trade_point_transactions', to=settings.AUTH_USER_MODEL)),
                ('membership', models.ForeignKey(help_text='Membership this Trade Point transaction belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='clients.membership')),
            ],
            options={
                'verbose_name': 'Trade Point',
                'verbose_name_plural': 'Trade Points',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['membership', 'created_at'], name='clients_tra_members_5cdd8b_idx'), models.Index(fields=['transaction_type'], name='clients_tra_transac_1e8f6d_idx'), models.Index(fields=['reason'], name='clients_tra_reason_5c26eb_idx')],
            },
        ),
    ]
