# Generated by Django 5.2.6 on 2026-07-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0028_alter_membership_trade_points_tradepoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='lifetime_trade_points',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Total Trade Points earned since becoming a member.'),
        ),
    ]
