# Generated by Django 5.2.6 on 2026-08-16 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0029_membership_lifetime_trade_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='clients.area'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='clients.area'),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prospects', to='clients.area'),
        ),
        migrations.AddField(
            model_name='client',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='clients.region'),
        ),
        migrations.AddField(
            model_name='lead',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='clients.region'),
        ),
        migrations.AddField(
            model_name='prospect',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prospects', to='clients.region'),
        ),
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='territories', to='clients.region')),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='territory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='areas', to='clients.territory'),
        ),
        migrations.AddField(
            model_name='client',
            name='territory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='clients.territory'),
        ),
        migrations.AddField(
            model_name='lead',
            name='territory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='clients.territory'),
        ),
        migrations.AddField(
            model_name='prospect',
            name='territory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prospects', to='clients.territory'),
        ),
        migrations.AddConstraint(
            model_name='territory',
            constraint=models.UniqueConstraint(fields=('region', 'code'), name='unique_territory_code_per_region'),
        ),
        migrations.AddConstraint(
            model_name='area',
            constraint=models.UniqueConstraint(fields=('territory', 'code'), name='unique_area_code_per_territory'),
        ),
    ]
