# Generated by Django 5.2.6 on 2026-08-17 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0030_area_region_alter_client_area_alter_lead_area_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='interested_in',
        ),
        migrations.RemoveField(
            model_name='prospect',
            name='categories',
        ),
        migrations.CreateModel(
            name='ClientProductInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=200)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_interests', to='clients.client')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LeadProductInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=200)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_interests', to='clients.lead')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProspectProductInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=200)),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_interests', to='clients.prospect')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
