# Generated by Django 5.2.6 on 2026-08-28 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0031_remove_client_categories_remove_lead_interested_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='location_captured_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
