# Generated by Django 5.2.6 on 2026-09-11 16:30

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0032_lead_latitude_lead_location_captured_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EndUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_user_type', models.CharField(choices=[('FUNERAL_BENEFICIARY', 'Funeral Beneficiary'), ('GENERAL', 'General End User')], db_index=True, default='FUNERAL_BENEFICIARY', max_length=30)),
                ('first_name', models.CharField(max_length=120)),
                ('surname', models.CharField(max_length=120)),
                ('end_user_number', models.CharField(db_index=True, editable=False, help_text='Unique TDM reference automatically assigned to the end user.', max_length=30, unique=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('whatsapp', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address_line1', models.CharField(blank=True, max_length=200)),
                ('address_line2', models.CharField(blank=True, max_length=200)),
                ('suburb', models.CharField(blank=True, max_length=120)),
                ('city', models.CharField(blank=True, choices=[('Johannesburg', 'Johannesburg'), ('Pretoria', 'Pretoria'), ('Centurion', 'Centurion'), ('Midrand', 'Midrand'), ('Sandton', 'Sandton'), ('Randburg', 'Randburg'), ('Roodepoort', 'Roodepoort'), ('Soweto', 'Soweto'), ('Alberton', 'Alberton'), ('Benoni', 'Benoni'), ('Boksburg', 'Boksburg'), ('Brakpan', 'Brakpan'), ('Edenvale', 'Edenvale'), ('Germiston', 'Germiston'), ('Kempton Park', 'Kempton Park'), ('Nigel', 'Nigel'), ('Springs', 'Springs'), ('Krugersdorp', 'Krugersdorp'), ('Randfontein', 'Randfontein'), ('Westonaria', 'Westonaria'), ('Carletonville', 'Carletonville'), ('Akasia', 'Akasia'), ('Atteridgeville', 'Atteridgeville'), ('Mamelodi', 'Mamelodi'), ('Soshanguve', 'Soshanguve'), ('Ga-Rankuwa', 'Ga-Rankuwa'), ('Bedfordview', 'Bedfordview'), ('Fourways', 'Fourways'), ('Bryanston', 'Bryanston'), ('Rosebank', 'Rosebank'), ('Melville', 'Melville'), ('Florida', 'Florida'), ('Lenasia', 'Lenasia'), ('Tembisa', 'Tembisa'), ('Daveyton', 'Daveyton'), ('Katlehong', 'Katlehong'), ('Vosloorus', 'Vosloorus'), ('Thokoza', 'Thokoza'), ('Tsakane', 'Tsakane'), ('Kwa-Thema', 'Kwa-Thema'), ('Other (Gauteng)', 'Other (Gauteng)')], max_length=120)),
                ('province', models.CharField(blank=True, choices=[('EC', 'Eastern Cape'), ('FS', 'Free State'), ('GP', 'Gauteng'), ('KZN', 'KwaZulu-Natal'), ('LP', 'Limpopo'), ('MP', 'Mpumalanga'), ('NC', 'Northern Cape'), ('NW', 'North West'), ('WC', 'Western Cape')], max_length=10)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(default='South Africa', max_length=120)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))])),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))])),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], db_index=True, default='ACTIVE', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_manager', models.ForeignKey(blank=True, help_text='Internal TDM staff member responsible for this end user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_end_users', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(help_text='TDM client through which this end user is served.', on_delete=django.db.models.deletion.CASCADE, related_name='end_users', to='clients.client')),
            ],
            options={
                'ordering': ['surname', 'first_name'],
                'indexes': [models.Index(fields=['client', 'surname'], name='clients_end_client__75067a_idx'), models.Index(fields=['client', 'end_user_number'], name='clients_end_client__97ac39_idx')],
            },
        ),
    ]
