# Generated by Django 5.2.6 on 2026-09-29 07:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0033_enduser'),
        ('products', '0012_productknowledgeuniteconomics'),
        ('tasks', '0004_alter_task_task_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Date and time the sample request was made.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined'), ('RETURNED', 'Returned')], db_index=True, default='PENDING', max_length=10)),
                ('expected_date', models.DateField(db_index=True, help_text='Expected sample date. Defaults to the next business day.')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the sample request.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prospect', models.ForeignKey(help_text='Prospect this sample request is for.', on_delete=django.db.models.deletion.CASCADE, related_name='sample_requests', to='clients.prospect')),
                ('requested_by', models.ForeignKey(blank=True, help_text='User who made the sample request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sample_requests_made', to=settings.AUTH_USER_MODEL)),
                ('task', models.OneToOneField(blank=True, help_text='Task created when the sample request is submitted and remains pending.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sample_request', to='tasks.task')),
            ],
            options={
                'ordering': ['-requested_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SampleRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Number of product units requested as a sample.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(help_text='Product being requested as a sample.', on_delete=django.db.models.deletion.PROTECT, related_name='sample_request_items', to='products.product')),
                ('sample_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='clients.samplerequest')),
            ],
            options={
                'ordering': ['product__name', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='samplerequest',
            index=models.Index(fields=['prospect', 'status'], name='clients_sam_prospec_95d3e0_idx'),
        ),
        migrations.AddIndex(
            model_name='samplerequest',
            index=models.Index(fields=['status', 'expected_date'], name='clients_sam_status_ecd72d_idx'),
        ),
        migrations.AddIndex(
            model_name='samplerequest',
            index=models.Index(fields=['requested_by', 'requested_at'], name='clients_sam_request_c0fa10_idx'),
        ),
        migrations.AddConstraint(
            model_name='samplerequestitem',
            constraint=models.UniqueConstraint(fields=('sample_request', 'product'), name='unique_sample_product_per_request'),
        ),
    ]
