# Generated by Django 5.2.6 on 2026-01-18 22:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_limit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('new_limit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_changed', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Funder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('weekly_rate_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Weekly percentage return charged on capped utilization.', max_digits=6)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Live balance you hold/owe after top-ups/payouts.', max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FunderAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['funder_id', 'client_id'],
            },
        ),
        migrations.CreateModel(
            name='FunderClientWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(help_text='ISO week Monday')),
                ('credit_limit_at_start', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('usage_sum', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('visible_utilization', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Usage capped at 100% of credit_limit for this client in the week.', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-week_start', 'funder_id', 'client_id'],
            },
        ),
        migrations.CreateModel(
            name='FunderMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('MANAGER', 'Manager'), ('VIEWER', 'Viewer')], default='VIEWER', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FunderMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('topup', 'Top-up (increase balance)'), ('payout', 'Payout (decrease balance)'), ('adjustment', 'Manual Adjustment')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FunderWeekSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(db_index=True, help_text='ISO week Monday')),
                ('visible_utilization_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('weekly_rate_pct_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('weekly_return', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount owed to the funder for this week (not including your margins).', max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-week_start', 'funder_id'],
            },
        ),
        migrations.CreateModel(
            name='CreditAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_term', models.CharField(choices=[('0D', '0 Day Account'), ('3D', '3 Day Account'), ('7D', '7 Day Account')], default='0D', help_text='How long the client has to settle credit purchases (e.g. 3 or 7 days).', max_length=3)),
                ('credit_deposit_pct', models.DecimalField(choices=[(Decimal('0.00'), '0%'), (Decimal('30.00'), '30%'), (Decimal('50.00'), '50%'), (Decimal('100.00'), '100%')], decimal_places=2, default=Decimal('100.00'), help_text='Deposit percentage required when using credit (0%, 30%, 50% or 100%).', max_digits=5)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('credit_used', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('next_due_date', models.DateField(blank=True, help_text='Next repayment due date (optional).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_account', to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='CreditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('usage', 'Credit Used'), ('repayment', 'Credit Repaid'), ('adjustment', 'Adjustment (Used)'), ('writeoff', 'Write-off'), ('issue', 'Credit Issued (Limit +)'), ('limit_decrease', 'Limit Decrease (Limit -)')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('posted_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_entries_created', to=settings.AUTH_USER_MODEL)),
                ('credit_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='credit.creditaccount')),
            ],
            options={
                'ordering': ['-posted_at', '-id'],
            },
        ),
    ]
