# Generated by Django 5.2.6 on 2025-09-29 19:19

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_client_price_type'),
        ('credit', '0001_initial'),
        ('invoices', '0004_invoice_credit_usage_applied'),
        ('transactions', '0004_alter_businessbalance_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('usage', 'Credit Used'), ('repayment', 'Credit Repaid'), ('adjustment', 'Adjustment'), ('writeoff', 'Write-off')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('posted_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-posted_at', '-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='creditlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='creditaccount',
            index=models.Index(fields=['client'], name='credit_cred_client__aaea79_idx'),
        ),
        migrations.AddIndex(
            model_name='creditlog',
            index=models.Index(fields=['credit_account', 'created_at'], name='credit_cred_credit__ce60d0_idx'),
        ),
        migrations.AddField(
            model_name='creditentry',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_entries_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditentry',
            name='credit_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='credit.creditaccount'),
        ),
        migrations.AddField(
            model_name='creditentry',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_entries', to='invoices.invoice'),
        ),
        migrations.AddField(
            model_name='creditentry',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_entries', to='transactions.transaction'),
        ),
        migrations.AddIndex(
            model_name='creditentry',
            index=models.Index(fields=['credit_account', 'posted_at'], name='credit_cred_credit__5934ac_idx'),
        ),
        migrations.AddIndex(
            model_name='creditentry',
            index=models.Index(fields=['kind', 'posted_at'], name='credit_cred_kind_0c6b11_idx'),
        ),
        migrations.AddIndex(
            model_name='creditentry',
            index=models.Index(fields=['invoice'], name='credit_cred_invoice_2b16e8_idx'),
        ),
    ]
