# Generated by Django 5.2.6 on 2026-01-18 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('credit', '0001_initial'),
        ('invoices', '0001_initial'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='creditentry',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_entries', to='invoices.invoice'),
        ),
        migrations.AddField(
            model_name='creditentry',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_entries', to='transactions.transaction'),
        ),
        migrations.AddField(
            model_name='creditlog',
            name='authorised_by',
            field=models.ForeignKey(blank=True, help_text='Who approved or made the credit change.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditlog',
            name='credit_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='credit.creditaccount'),
        ),
        migrations.AddField(
            model_name='creditaccount',
            name='funder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_accounts', to='credit.funder'),
        ),
        migrations.AddField(
            model_name='funderallocation',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funder_allocations', to='clients.client'),
        ),
        migrations.AddField(
            model_name='funderallocation',
            name='funder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='credit.funder'),
        ),
        migrations.AddField(
            model_name='funder',
            name='allocated_clients',
            field=models.ManyToManyField(blank=True, help_text='Clients this funder has capital allocated to.', related_name='funders', through='credit.FunderAllocation', to='clients.client'),
        ),
        migrations.AddField(
            model_name='funderclientweek',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funder_weeks', to='clients.client'),
        ),
        migrations.AddField(
            model_name='funderclientweek',
            name='funder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_weeks', to='credit.funder'),
        ),
        migrations.AddField(
            model_name='fundermember',
            name='funder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='credit.funder'),
        ),
        migrations.AddField(
            model_name='fundermember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funder_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fundermovement',
            name='funder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='credit.funder'),
        ),
        migrations.AddField(
            model_name='funderweeksummary',
            name='funder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week_summaries', to='credit.funder'),
        ),
        migrations.AddIndex(
            model_name='creditentry',
            index=models.Index(fields=['credit_account', 'posted_at'], name='credit_cred_credit__5934ac_idx'),
        ),
        migrations.AddIndex(
            model_name='creditentry',
            index=models.Index(fields=['kind', 'posted_at'], name='credit_cred_kind_0c6b11_idx'),
        ),
        migrations.AddIndex(
            model_name='creditentry',
            index=models.Index(fields=['invoice'], name='credit_cred_invoice_2b16e8_idx'),
        ),
        migrations.AddIndex(
            model_name='creditlog',
            index=models.Index(fields=['credit_account', 'created_at'], name='credit_cred_credit__ce60d0_idx'),
        ),
        migrations.AddIndex(
            model_name='creditaccount',
            index=models.Index(fields=['client'], name='credit_cred_client__aaea79_idx'),
        ),
        migrations.AddIndex(
            model_name='creditaccount',
            index=models.Index(fields=['funder'], name='credit_cred_funder__106a99_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='funderallocation',
            unique_together={('funder', 'client')},
        ),
        migrations.AddIndex(
            model_name='funderclientweek',
            index=models.Index(fields=['funder', 'week_start'], name='credit_fund_funder__1caa73_idx'),
        ),
        migrations.AddIndex(
            model_name='funderclientweek',
            index=models.Index(fields=['client', 'week_start'], name='credit_fund_client__91e9cc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='funderclientweek',
            unique_together={('funder', 'client', 'week_start')},
        ),
        migrations.AddIndex(
            model_name='fundermember',
            index=models.Index(fields=['funder'], name='credit_fund_funder__4f1891_idx'),
        ),
        migrations.AddIndex(
            model_name='fundermember',
            index=models.Index(fields=['user'], name='credit_fund_user_id_de8127_idx'),
        ),
        migrations.AddIndex(
            model_name='fundermember',
            index=models.Index(fields=['is_active'], name='credit_fund_is_acti_3130d0_idx'),
        ),
        migrations.AddConstraint(
            model_name='fundermember',
            constraint=models.UniqueConstraint(fields=('funder', 'user'), name='uniq_funder_user'),
        ),
        migrations.AddIndex(
            model_name='fundermovement',
            index=models.Index(fields=['funder', 'created_at'], name='credit_fund_funder__fb1db6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='funderweeksummary',
            unique_together={('funder', 'week_start')},
        ),
    ]
