# Generated by Django 5.2.6 on 2025-09-29 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0002_creditentry_alter_creditlog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditentry',
            name='reference',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
