# Generated by Django 5.2.6 on 2026-01-19 12:06

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_initial'),
        ('credit', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='funderclientweek',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='funderclientweek',
            name='client',
        ),
        migrations.RemoveField(
            model_name='funderclientweek',
            name='funder',
        ),
        migrations.RemoveIndex(
            model_name='creditentry',
            name='credit_cred_invoice_2b16e8_idx',
        ),
        migrations.AlterField(
            model_name='creditaccount',
            name='credit_deposit_pct',
            field=models.DecimalField(choices=[(Decimal('0.00'), '0%'), (Decimal('30.00'), '30%'), (Decimal('50.00'), '50%'), (Decimal('100.00'), '100%')], decimal_places=2, default=Decimal('100.00'), help_text='Deposit required when using credit.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='creditaccount',
            name='payment_term',
            field=models.CharField(choices=[('0D', '0 Day (Cash)'), ('3D', '3 Day Credit'), ('7D', '7 Day Credit')], default='0D', help_text='How long the client has to settle credit purchases.', max_length=3),
        ),
        migrations.AlterField(
            model_name='creditentry',
            name='kind',
            field=models.CharField(choices=[('usage', 'Credit Used'), ('repayment', 'Credit Repaid'), ('adjustment', 'Adjustment'), ('writeoff', 'Write-off'), ('issue', 'Limit Increase'), ('limit_decrease', 'Limit Decrease')], max_length=16),
        ),
        migrations.AlterField(
            model_name='creditlog',
            name='authorised_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='funder',
            name='allocated_clients',
            field=models.ManyToManyField(blank=True, related_name='funders', through='credit.FunderAllocation', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='funder',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Live balance held for this funder.', max_digits=14),
        ),
        migrations.AlterField(
            model_name='fundermovement',
            name='kind',
            field=models.CharField(choices=[('topup', 'Top-up'), ('payout', 'Payout'), ('adjustment', 'Manual Adjustment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='funderweeksummary',
            name='visible_utilization_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of capped client utilization for the week.', max_digits=14),
        ),
        migrations.AlterField(
            model_name='funderweeksummary',
            name='weekly_rate_pct_snapshot',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Weekly rate at time of calculation.', max_digits=6),
        ),
        migrations.AlterField(
            model_name='funderweeksummary',
            name='weekly_return',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount owed to funder for the week.', max_digits=14),
        ),
        migrations.AddIndex(
            model_name='funderweeksummary',
            index=models.Index(fields=['funder', 'week_start'], name='credit_fund_funder__18c848_idx'),
        ),
        migrations.DeleteModel(
            name='FunderClientWeek',
        ),
    ]
