# Generated by Django 5.2.6 on 2026-03-03 16:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0003_alter_funderclientweek_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditentry',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Running available credit after this entry.', max_digits=12),
        ),
    ]
