# Generated by Django 5.2.6 on 2025-11-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0003_creditentry_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditentry',
            name='kind',
            field=models.CharField(choices=[('usage', 'Credit Used'), ('repayment', 'Credit Repaid'), ('adjustment', 'Adjustment (Used)'), ('writeoff', 'Write-off'), ('issue', 'Credit Issued (Limit +)'), ('limit_decrease', 'Limit Decrease (Limit -)')], max_length=16),
        ),
    ]
