# Generated by Django 5.2.6 on 2025-11-09 14:03

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_client_price_type'),
        ('credit', '0004_alter_creditentry_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('weekly_rate_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Weekly percentage return charged on capped utilization.', max_digits=6)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Live balance you hold/owe after top-ups/payouts.', max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FunderClientWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(help_text='ISO week Monday')),
                ('credit_limit_at_start', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('usage_sum', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('visible_utilization', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Usage capped at 100% of credit_limit for this client in the week.', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funder_weeks', to='clients.client')),
                ('funder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_weeks', to='credit.funder')),
            ],
            options={
                'ordering': ['-week_start', 'funder_id', 'client_id'],
                'indexes': [models.Index(fields=['funder', 'week_start'], name='credit_fund_funder__1caa73_idx'), models.Index(fields=['client', 'week_start'], name='credit_fund_client__91e9cc_idx')],
                'unique_together': {('funder', 'client', 'week_start')},
            },
        ),
        migrations.CreateModel(
            name='FunderMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('topup', 'Top-up (increase balance)'), ('payout', 'Payout (decrease balance)'), ('adjustment', 'Manual Adjustment')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('funder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='credit.funder')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['funder', 'created_at'], name='credit_fund_funder__fb1db6_idx')],
            },
        ),
        migrations.CreateModel(
            name='FunderWeekSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(db_index=True, help_text='ISO week Monday')),
                ('visible_utilization_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('weekly_rate_pct_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('weekly_return', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount owed to the funder for this week (not including your margins).', max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('funder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week_summaries', to='credit.funder')),
            ],
            options={
                'ordering': ['-week_start', 'funder_id'],
                'unique_together': {('funder', 'week_start')},
            },
        ),
    ]
