# Generated by Django 5.2.6 on 2026-03-11 07:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0004_creditentry_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='funderweeksummary',
            name='raw_weekly_usage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total credit usage recorded this week before applying the funder cap.', max_digits=14),
        ),
    ]
