# Generated by Django 5.2.6 on 2025-11-10 14:26

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_client_funder'),
        ('credit', '0005_funder_funderclientweek_fundermovement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunderAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['funder_id', 'client_id'],
            },
        ),
        migrations.AddField(
            model_name='creditaccount',
            name='funder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_accounts', to='credit.funder'),
        ),
        migrations.AddIndex(
            model_name='creditaccount',
            index=models.Index(fields=['funder'], name='credit_cred_funder__106a99_idx'),
        ),
        migrations.AddField(
            model_name='funderallocation',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funder_allocations', to='clients.client'),
        ),
        migrations.AddField(
            model_name='funderallocation',
            name='funder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='credit.funder'),
        ),
        migrations.AlterUniqueTogether(
            name='funderallocation',
            unique_together={('funder', 'client')},
        ),
    ]
