# Generated by Django 5.2.6 on 2026-03-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0005_funderweeksummary_raw_weekly_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='funder',
            name='is_dummy',
            field=models.BooleanField(default=False, help_text='Indicates whether this funder is for internal/dummy use only.'),
        ),
    ]
