# Generated by Django 5.2.6 on 2025-11-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_client_funder'),
        ('credit', '0006_funderallocation_creditaccount_funder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funder',
            name='allocated_clients',
            field=models.ManyToManyField(blank=True, help_text='Clients this funder has capital allocated to.', related_name='funders', through='credit.FunderAllocation', to='clients.client'),
        ),
    ]
