# Generated by Django 5.2.6 on 2026-03-20 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0006_funder_is_dummy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundermember',
            name='funder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='credit.funder'),
        ),
    ]
