# Generated by Django 5.2.6 on 2026-03-20 17:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0007_alter_fundermember_funder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='fundermember',
            name='uniq_funder_user',
        ),
        migrations.AlterField(
            model_name='fundermember',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Admin'), ('VIEWER', 'Viewer')], default='VIEWER', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='fundermember',
            constraint=models.UniqueConstraint(condition=models.Q(('funder__isnull', False)), fields=('funder', 'user'), name='uniq_funder_user'),
        ),
    ]
