# Generated by Django 5.2.6 on 2025-11-12 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0007_funder_allocated_clients'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FunderMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('MANAGER', 'Manager'), ('VIEWER', 'Viewer')], default='VIEWER', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('funder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='credit.funder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funder_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['funder'], name='credit_fund_funder__4f1891_idx'), models.Index(fields=['user'], name='credit_fund_user_id_de8127_idx'), models.Index(fields=['is_active'], name='credit_fund_is_acti_3130d0_idx')],
                'constraints': [models.UniqueConstraint(fields=('funder', 'user'), name='uniq_funder_user')],
            },
        ),
    ]
