# Generated by Django 5.2.6 on 2025-12-07 11:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0008_fundermember'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditaccount',
            name='credit_deposit_pct',
            field=models.DecimalField(choices=[(Decimal('0.00'), '0%'), (Decimal('30.00'), '30%'), (Decimal('50.00'), '50%'), (Decimal('100.00'), '100%')], decimal_places=2, default=Decimal('100.00'), help_text='Deposit percentage required when using credit (0%, 30%, 50% or 100%).', max_digits=5),
        ),
        migrations.AddField(
            model_name='creditaccount',
            name='payment_term',
            field=models.CharField(choices=[('0D', '0 Day Account'), ('3D', '3 Day Account'), ('7D', '7 Day Account')], default='0D', help_text='How long the client has to settle credit purchases (e.g. 3 or 7 days).', max_length=3),
        ),
    ]
