# Generated by Django 5.2.6 on 2026-04-19 09:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0008_remove_fundermember_uniq_funder_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funder',
            name='profit_frequency',
            field=models.CharField(choices=[('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('MANUAL', 'Manual')], default='WEEKLY', help_text='How often this funder expects profit processing.', max_length=12),
        ),
        migrations.AddField(
            model_name='funder',
            name='profit_mode',
            field=models.CharField(choices=[('PAYOUT', 'Payout'), ('REINVEST', 'Reinvest')], default='PAYOUT', help_text='Determines whether profit is paid out or added back into the funder balance.', max_length=12),
        ),
        migrations.AlterField(
            model_name='creditaccount',
            name='credit_deposit_pct',
            field=models.DecimalField(choices=[(Decimal('0.00'), '0%'), (Decimal('30.00'), '30%'), (Decimal('50.00'), '50%'), (Decimal('100.00'), '100%')], decimal_places=2, default=Decimal('100.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='creditaccount',
            name='next_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creditaccount',
            name='payment_term',
            field=models.CharField(choices=[('0D', '0 Day (Cash)'), ('3D', '3 Day Credit'), ('7D', '7 Day Credit')], default='0D', max_length=3),
        ),
    ]
