# Generated by Django 5.2.6 on 2026-04-19 10:04

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0009_funder_profit_frequency_funder_profit_mode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunderProfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('WEEKLY', 'Weekly Summary'), ('MONTHLY', 'Monthly Summary'), ('MANUAL', 'Manual')], default='WEEKLY', max_length=12)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Profit amount for the selected period.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID_OUT', 'Paid Out'), ('REINVESTED', 'Reinvested'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=12)),
                ('processed_at', models.DateTimeField(blank=True, help_text='When this profit was paid out or reinvested.', null=True)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('funder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profits', to='credit.funder')),
                ('week_summary', models.ForeignKey(blank=True, help_text='Optional link to the weekly summary that generated this profit.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profit_entries', to='credit.funderweeksummary')),
            ],
            options={
                'ordering': ['-period_start', '-created_at'],
                'indexes': [models.Index(fields=['funder', 'status'], name='credit_fund_funder__f44570_idx'), models.Index(fields=['funder', 'period_start', 'period_end'], name='credit_fund_funder__e6fe1a_idx')],
            },
        ),
    ]
