# Generated by Django 5.2.6 on 2025-12-30 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0009_creditaccount_credit_deposit_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditaccount',
            name='next_due_date',
            field=models.DateField(blank=True, help_text='Next repayment due date (optional).', null=True),
        ),
    ]
