# Generated by Django 5.2.6 on 2026-04-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0010_funderprofit'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundermovement',
            name='profit_links',
            field=models.ManyToManyField(blank=True, help_text='Optional profit entries linked to this movement.', related_name='movements', to='credit.funderprofit'),
        ),
    ]
