# Generated by Django 5.2.6 on 2025-09-14 19:31

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0004_client_account_type_alter_client_credit_status'),
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('payment', 'Payment In'), ('invoice', 'Invoice Out'), ('credit_issue', 'Credit Issued'), ('credit_usage', 'Credit Used'), ('credit_repayment', 'Credit Repaid'), ('refund', 'Refund'), ('adjustment', 'Manual Adjustment')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Account balance after this transaction.', max_digits=12)),
                ('reference', models.CharField(blank=True, help_text='Payment ref, invoice number, etc.', max_length=100)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='clients.client')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='invoices.invoice')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', 'transaction_type', 'created_at'], name='transaction_client__c38812_idx')],
            },
        ),
    ]
