# Generated by Django 5.2.6 on 2025-09-15 14:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Seshibo Daily Market', max_length=64, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_in', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_out', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Business Balance',
                'verbose_name_plural': 'Business Balance',
            },
        ),
        migrations.AlterField(
            model_name='transaction',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Business balance immediately after this transaction.', max_digits=12),
        ),
    ]
