# Generated by Django 5.2.6 on 2025-09-17 20:55

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_account_type_alter_client_credit_status'),
        ('transactions', '0002_businessbalance_alter_transaction_balance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessbalance',
            options={},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AddField(
            model_name='transaction',
            name='client_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Client balance immediately after this transaction.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='ClientBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_in', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_out', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance_row', to='clients.client')),
            ],
        ),
    ]
