# Generated by Django 5.2.6 on 2025-09-18 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_businessbalance_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessbalance',
            options={'verbose_name': 'Business balance', 'verbose_name_plural': 'Business balances'},
        ),
        migrations.AlterModelOptions(
            name='clientbalance',
            options={'verbose_name': 'Client balance', 'verbose_name_plural': 'Client balances'},
        ),
    ]
