# Generated by Django 5.2.6 on 2025-10-22 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('business_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=64)),
                ('location', models.CharField(max_length=255)),
                ('product_type', models.CharField(choices=[('poultry_whole', 'Poultry — Whole'), ('poultry_portions', 'Poultry — Portions'), ('eggs', 'Eggs'), ('produce', 'Produce'), ('dairy', 'Dairy'), ('dry', 'Dry Goods / Staples'), ('other', 'Other')], max_length=32)),
                ('weekly_capacity', models.CharField(max_length=128)),
                ('packaging', models.CharField(blank=True, max_length=255)),
                ('certification_file', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('delivery', models.CharField(choices=[('deliver', 'Deliver'), ('collect', 'Collect'), ('either', 'Either')], max_length=16)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=32)),
            ],
        ),
    ]
