# Generated by Django 5.2.6 on 2026-01-18 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text="Small text above the title, e.g. 'Limited time', 'New'.", max_length=50)),
                ('title', models.CharField(max_length=120)),
                ('subtitle', models.TextField(blank=True)),
                ('slide_image', models.ImageField(blank=True, null=True, upload_to='hero_slides/')),
                ('button_text', models.CharField(blank=True, default='View offer', max_length=40)),
                ('link_url', models.URLField(blank=True, help_text='Optional link when user clicks the button.')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SupplierLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('business_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=64)),
                ('location', models.CharField(max_length=255)),
                ('product_type', models.CharField(choices=[('poultry_whole', 'Poultry — Whole'), ('poultry_portions', 'Poultry — Portions'), ('eggs', 'Eggs'), ('produce', 'Produce'), ('dairy', 'Dairy'), ('dry', 'Dry Goods / Staples'), ('other', 'Other')], max_length=32)),
                ('weekly_capacity', models.CharField(max_length=128)),
                ('packaging', models.CharField(blank=True, max_length=255)),
                ('certification_file', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('delivery', models.CharField(choices=[('deliver', 'Deliver'), ('collect', 'Collect'), ('either', 'Either')], max_length=16)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=32)),
            ],
        ),
    ]
