# Generated by Django 5.2.6 on 2025-12-06 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text="Small text above the title, e.g. 'Limited time', 'New'.", max_length=50)),
                ('title', models.CharField(max_length=120)),
                ('subtitle', models.TextField(blank=True)),
                ('button_text', models.CharField(blank=True, default='View offer', max_length=40)),
                ('link_url', models.URLField(blank=True, help_text='Optional link when user clicks the button.')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
