# Generated by Django 5.2.6 on 2025-12-06 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_heroslide'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroslide',
            name='slide_image',
            field=models.ImageField(blank=True, null=True, upload_to='hero_slides/'),
        ),
    ]
