# Generated by Django 5.2.6 on 2026-04-22 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_payments', '0002_rename_ozow_transaction_id_payment_idempotency_key_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='institution_id',
            new_name='ozow_transaction_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='institution_name',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='oneapi_payment_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='oneapi_transaction_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_method',
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('ozow', 'Ozow'), ('yoco', 'Yoco')], max_length=20),
        ),
    ]
