# Generated by Django 5.2.6 on 2026-05-04 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_payments', '0003_rename_institution_id_payment_ozow_transaction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('ozow', 'Ozow'), ('eft', 'Direct EFT'), ('cash_deposit', 'Cash Deposit')], max_length=20),
        ),
    ]
