# Generated by Django 5.2.6 on 2025-10-30 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='department',
            field=models.CharField(choices=[('SUPPORT', 'Support'), ('ACCOUNTS', 'Accounts'), ('SALES', 'Sales'), ('COMPLIANCE', 'Compliance'), ('PRODUCT', 'Product'), ('OPERATIONS', 'Operations')], db_index=True, default='SUPPORT', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('OPEN', 'Open'), ('Closed', 'Closed')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
