# Generated by Django 5.2.6 on 2026-04-22 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0017_client_is_dummy'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('is_internal', models.BooleanField(default=True, help_text='Internal note vs external/customer-facing comment.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_closed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='source',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('SYSTEM', 'System'), ('WORKFLOW', 'Workflow'), ('CLIENT_ACTION', 'Client Action'), ('FOLLOW_UP', 'Follow-up')], db_index=True, default='MANUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('GENERAL', 'General'), ('CLIENT_REVIEW', 'Client Review'), ('CLIENT_ACTIVATION', 'Client Activation'), ('COMPLIANCE_DOCUMENT', 'Compliance Document'), ('ORDER_FOLLOW_UP', 'Order Follow-up'), ('DELIVERY_PREPARATION', 'Delivery Preparation'), ('DELIVERY_CONFIRMATION', 'Delivery Confirmation'), ('PAYMENT_FOLLOW_UP', 'Payment Follow-up'), ('INVOICE_REVIEW', 'Invoice Review'), ('CREDIT_REVIEW', 'Credit Review')], db_index=True, default='GENERAL', max_length=40),
        ),
        migrations.AlterField(
            model_name='task',
            name='department',
            field=models.CharField(choices=[('SUPPORT', 'Support'), ('ACCOUNTS', 'Accounts'), ('SALES', 'Sales'), ('COMPLIANCE', 'Compliance'), ('SUPPLY_CHAIN', 'Supply Chain'), ('OPERATIONS', 'Operations'), ('LOGISTICS', 'Logistics'), ('FINANCE', 'Finance')], db_index=True, default='SUPPORT', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('OPEN', 'Open'), ('CLOSED', 'Closed')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=180)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('OPEN', 'Open'), ('PENDING', 'Pending'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], db_index=True, default='NEW', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], db_index=True, default='MEDIUM', max_length=10)),
                ('department', models.CharField(choices=[('SUPPORT', 'Support'), ('ACCOUNTS', 'Accounts'), ('SALES', 'Sales'), ('COMPLIANCE', 'Compliance'), ('SUPPLY_CHAIN', 'Supply Chain'), ('OPERATIONS', 'Operations'), ('LOGISTICS', 'Logistics'), ('FINANCE', 'Finance')], db_index=True, default='SUPPORT', max_length=20)),
                ('ticket_type', models.CharField(choices=[('GENERAL_ENQUIRY', 'General Enquiry'), ('SALES_ENQUIRY', 'Sales Enquiry'), ('CLIENT_SUPPORT', 'Client Support'), ('DELIVERY_ISSUE', 'Delivery Issue'), ('PAYMENT_ISSUE', 'Payment Issue'), ('ACCOUNT_ISSUE', 'Account Issue'), ('SYSTEM_GLITCH', 'System Glitch'), ('COMPLAINT', 'Complaint'), ('OTHER', 'Other')], db_index=True, default='GENERAL_ENQUIRY', max_length=30)),
                ('source', models.CharField(choices=[('WEBSITE', 'Website'), ('EMAIL', 'Email'), ('PHONE', 'Phone'), ('WHATSAPP', 'WhatsApp'), ('INTERNAL', 'Internal'), ('SYSTEM', 'System'), ('WALK_IN', 'Walk-in'), ('OTHER', 'Other')], db_index=True, default='WEBSITE', max_length=20)),
                ('requester_name', models.CharField(blank=True, max_length=160)),
                ('requester_email', models.EmailField(blank=True, max_length=254)),
                ('requester_phone', models.CharField(blank=True, max_length=50)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='clients.client')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_closed', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.ticket'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['task_type'], name='tasks_task_task_ty_45f0a7_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['source'], name='tasks_task_source_99cbe2_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['content_type', 'object_id'], name='tasks_task_content_2bbe5a_idx'),
        ),
        migrations.AddField(
            model_name='ticketcomment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticketcomment',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tasks.ticket'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', 'priority'], name='tasks_ticke_status_75bf66_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['department'], name='tasks_ticke_departm_9bf365_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['ticket_type'], name='tasks_ticke_ticket__42759d_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['source'], name='tasks_ticke_source_27a899_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['client'], name='tasks_ticke_client__5cb17a_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['content_type', 'object_id'], name='tasks_ticke_content_d98244_idx'),
        ),
    ]
