# Generated by Django 5.2.6 on 2026-04-23 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tasks', '0002_ticketcomment_task_closed_by_task_opened_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('DEPARTMENT', 'Department')], db_index=True, max_length=20)),
                ('department', models.CharField(blank=True, choices=[('SUPPORT', 'Support'), ('ACCOUNTS', 'Accounts'), ('SALES', 'Sales'), ('COMPLIANCE', 'Compliance'), ('SUPPLY_CHAIN', 'Supply Chain'), ('OPERATIONS', 'Operations'), ('LOGISTICS', 'Logistics'), ('FINANCE', 'Finance')], db_index=True, max_length=20, null=True)),
                ('notification_type', models.CharField(choices=[('TASK', 'Task'), ('TICKET', 'Ticket')], db_index=True, max_length=10)),
                ('is_opened', models.BooleanField(db_index=True, default=False)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_notifications', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['scope', 'is_opened'], name='tasks_notif_scope_805e72_idx'), models.Index(fields=['recipient', 'is_opened'], name='tasks_notif_recipie_eb8c7f_idx'), models.Index(fields=['department', 'is_opened'], name='tasks_notif_departm_b775ab_idx')],
            },
        ),
    ]
