# Generated by Django 5.2.6 on 2026-09-29 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('GENERAL', 'General'), ('LEAD_QUALIFICATION', 'Lead Qualification'), ('CLIENT_REVIEW', 'Client Review'), ('CLIENT_ACTIVATION', 'Client Activation'), ('COMPLIANCE_DOCUMENT', 'Compliance Document'), ('ORDER_FOLLOW_UP', 'Order Follow-up'), ('DELIVERY_PREPARATION', 'Delivery Preparation'), ('DELIVERY_CONFIRMATION', 'Delivery Confirmation'), ('PAYMENT_FOLLOW_UP', 'Payment Follow-up'), ('INVOICE_REVIEW', 'Invoice Review'), ('CREDIT_REVIEW', 'Credit Review'), ('SAMPLE_REQUEST', 'Sample Request')], db_index=True, default='GENERAL', max_length=40),
        ),
    ]
