# Generated by Django 5.2.6 on 2026-05-27 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_salesrepprofile_base_commission_pct_and_more'),
        ('tasks', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='sales_operator',
            field=models.ForeignKey(blank=True, help_text='Sales operator linked to this ticket.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='profiles.salesoperator'),
        ),
    ]
