# Generated by Django 5.2.6 on 2025-09-14 16:02

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='orderitem',
            name='orders_orde_order_i_5d347b_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderitem',
            name='orders_orde_categor_7610ac_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderitem',
            name='orders_orde_product_32ff41_idx',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='added_at',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='line_total_excl',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='line_total_inc',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='line_vat_amount',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='supplier',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(blank=True, help_text='Snapshot of product name at order time.', max_length=220),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='sku',
            field=models.CharField(blank=True, help_text='Snapshot of product SKU at order time.', max_length=64),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price_excl',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='uom',
            field=models.CharField(blank=True, choices=[('EA', 'Each'), ('KG', 'Kilogram'), ('L', 'Litre'), ('PK', 'Pack'), ('BOX', 'Box')], max_length=8),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='vat_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
    ]
