# Generated by Django 5.2.6 on 2026-01-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('awaiting_payment', 'Awaiting Payment'), ('at_warehouse', 'At Warehouse'), ('ready_for_delivery', 'Ready for Delivery'), ('out_for_delivery', 'Out for Delivery'), ('complete', 'Complete'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], default='pending', max_length=25),
        ),
    ]
