# Generated by Django 5.2.6 on 2025-09-14 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderitem_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_payment_63e120_idx',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='order',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who approved the order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who reviewed the order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('ready_for_delivery', 'Ready for Delivery'), ('out_for_delivery', 'Out for Delivery'), ('complete', 'Complete'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], default='pending', max_length=25),
        ),
    ]
