# Generated by Django 5.2.6 on 2026-02-20 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('awaiting_payment', 'Awaiting Payment'), ('at_warehouse', 'At Warehouse'), ('ready_for_delivery', 'Ready for Delivery'), ('out_for_delivery', 'Out for Delivery'), ('complete', 'Complete'), ('returned', 'Returned'), ('cancelled', 'Cancelled'), ('credit_blocked', 'Credit Blocked')], default='pending', max_length=25),
        ),
        migrations.CreateModel(
            name='OrderAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('status_changed', 'Status Changed'), ('credit_blocked', 'Credit Blocked'), ('approved', 'Approved'), ('cancelled', 'Cancelled'), ('deleted', 'Deleted')], max_length=32)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('status_before', models.CharField(blank=True, max_length=32)),
                ('status_after', models.CharField(blank=True, max_length=32)),
                ('amount_before', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('amount_after', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('snapshot_before', models.JSONField(blank=True, null=True)),
                ('snapshot_after', models.JSONField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_entries', to='orders.order')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-performed_at', '-id'],
                'indexes': [models.Index(fields=['order', 'performed_at'], name='orders_orde_order_i_a9c09c_idx'), models.Index(fields=['action'], name='orders_orde_action_d03c47_idx')],
            },
        ),
    ]
