# Generated by Django 5.2.6 on 2026-03-11 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_orders_orde_status_c6dd84_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderaudit',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='orders.order'),
        ),
    ]
