# Generated by Django 5.2.6 on 2026-01-03 07:55

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price_excl',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Will store price INCLUDING VAT (from wholesale_price_inc).', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
