# Generated by Django 5.2.6 on 2026-05-06 16:58

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0017_client_is_dummy'),
        ('orders', '0006_alter_orderaudit_order'),
        ('products', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], db_index=True, default='draft', max_length=20)),
                ('customer_notes', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('discount_total_excl', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('delivery_fee_excl', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('delivery_fee_vat_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('subtotal_excl', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('vat_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('grand_total_inc', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations_accepted', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='clients.client')),
                ('converted_order', models.OneToOneField(blank=True, help_text='Order created from this quotation, if converted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_quotation', to='orders.order')),
                ('created_by', models.ForeignKey(blank=True, help_text='Logged-in user who created this quotation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=64)),
                ('product_name', models.CharField(blank=True, max_length=220)),
                ('uom', models.CharField(blank=True, choices=[('EA', 'Each'), ('KG', 'Kilogram'), ('L', 'Litre'), ('PK', 'Pack'), ('BOX', 'Box')], max_length=8)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('unit_price_excl', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('unit_price_inc', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('discount_excl', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('vat_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotation_items', to='products.category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotation_items', to='products.product')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.quotation')),
            ],
            options={
                'ordering': ['quotation_id', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['client', 'status'], name='orders_quot_client__689eb9_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['quotation_date'], name='orders_quot_quotati_d30274_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['valid_until'], name='orders_quot_valid_u_d40e6d_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['created_by'], name='orders_quot_created_ece026_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['converted_order'], name='orders_quot_convert_a48d0a_idx'),
        ),
        migrations.AddIndex(
            model_name='quotationitem',
            index=models.Index(fields=['quotation', 'product'], name='orders_quot_quotati_bb8f57_idx'),
        ),
    ]
