# Generated by Django 5.2.6 on 2026-05-08 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0017_client_is_dummy'),
        ('orders', '0007_quotation_quotationitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='prospect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='clients.prospect'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='converted_order',
            field=models.OneToOneField(blank=True, help_text='Order created from this quotation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_quotation', to='orders.order'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['prospect', 'status'], name='orders_quot_prospec_b4a75b_idx'),
        ),
    ]
