# Generated by Django 5.2.6 on 2026-05-11 06:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_quotation_prospect_alter_quotation_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='public_token',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
