# Generated by Django 5.2.6 on 2026-05-11 09:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_quotation_public_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='public_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
