# Generated by Django 5.2.6 on 2026-05-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_quotation_public_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='public_decision_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='public_decision_user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
