# Generated by Django 5.2.6 on 2026-09-11 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0033_enduser'),
        ('orders', '0011_quotation_public_decision_ip_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='end_user',
            field=models.ForeignKey(blank=True, help_text='End user receiving or benefiting from this order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='clients.enduser'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='end_user',
            field=models.ForeignKey(blank=True, help_text='End user receiving or benefiting from this quotation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='clients.enduser'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['end_user', 'status'], name='orders_quot_end_use_37c978_idx'),
        ),
    ]
