# Generated by Django 5.2.6 on 2026-02-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesJobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('suburb', models.CharField(max_length=150)),
                ('town_or_city', models.CharField(max_length=150)),
                ('where_grew_up', models.CharField(help_text='Town / area where the applicant grew up', max_length=255)),
                ('sales_experience_summary', models.TextField(help_text='Overall sales experience summary')),
                ('previous_workplaces', models.TextField(help_text='Places they have worked before')),
                ('responsibilities', models.TextField(help_text='Key responsibilities held in previous roles')),
                ('lessons_learned', models.TextField(help_text='What they learned from previous roles')),
                ('client_identification_strategy', models.TextField(help_text='How they would identify potential clients')),
                ('pitching_strategy', models.TextField(help_text='How they would pitch FMCG products')),
                ('conversion_strategy', models.TextField(help_text='How they convert prospects into customers')),
                ('client_management_strategy', models.TextField(help_text='How they manage and retain clients')),
                ('resources_needed', models.TextField(help_text='Resources they believe they need to perform well')),
                ('has_drivers_license', models.BooleanField(default=False)),
                ('has_vehicle_access', models.BooleanField(default=False)),
                ('has_laptop_or_tablet', models.BooleanField(default=False)),
                ('can_work_in_team', models.BooleanField(default=True)),
                ('leadership_skills_description', models.TextField(blank=True, help_text='Leadership experience or skills')),
                ('comfortable_township_clients', models.BooleanField(default=False)),
                ('comfortable_suburban_clients', models.BooleanField(default=False)),
                ('comfortable_remote_work', models.BooleanField(default=False)),
                ('comfortable_startup_environment', models.BooleanField(default=False)),
                ('current_job', models.CharField(blank=True, help_text='Current job, if any', max_length=255)),
                ('availability_to_start', models.CharField(help_text='How soon they can start (e.g. immediately, 2 weeks)', max_length=100)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('shortlisted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
