# Generated by Django 5.2.6 on 2026-02-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesjobapplication',
            name='email',
            field=models.EmailField(default='unknown@example.com', help_text='Primary contact email address', max_length=254),
            preserve_default=False,
        ),
    ]
