# Generated by Django 5.2.6 on 2026-02-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_salesjobapplication_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesjobapplication',
            name='interview_status',
            field=models.CharField(choices=[('NONE', 'Not Invited'), ('INVITED', 'Invited to Interview'), ('BOOKED', 'Interview Booked'), ('COMPLETED', 'Interview Completed')], default='NONE', max_length=20),
        ),
    ]
