# Generated by Django 5.2.6 on 2026-02-18 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_salesjobapplication_interview_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesjobapplication',
            name='evaluator_notes',
            field=models.TextField(blank=True, help_text='Internal notes about this candidate'),
        ),
        migrations.AddField(
            model_name='salesjobapplication',
            name='overall_rating',
            field=models.IntegerField(blank=True, choices=[(1, '1 - Very Weak'), (2, '2 - Weak'), (3, '3 - Average'), (4, '4 - Strong'), (5, '5 - Exceptional')], help_text='Internal rating from 1 (Very Weak) to 5 (Exceptional)', null=True),
        ),
    ]
