# Generated by Django 5.2.6 on 2026-05-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_salesjobapplication_evaluator_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('territory', models.CharField(choices=[('SOUTH_WEST', 'South / West'), ('NORTH_CENTRAL', 'North / Central')], max_length=30)),
                ('first_name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('race', models.CharField(blank=True, choices=[('AFRICAN', 'African / Black'), ('COLOURED', 'Coloured'), ('INDIAN', 'Indian / Asian'), ('WHITE', 'White'), ('OTHER', 'Other'), ('PREFER_NOT_TO_SAY', 'Prefer Not To Say')], max_length=30)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('PREFER_NOT_TO_SAY', 'Prefer Not To Say')], max_length=30)),
                ('phone_number', models.CharField(max_length=30)),
                ('whatsapp_number', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('current_location', models.CharField(help_text='Current suburb / township / area where applicant lives', max_length=255)),
                ('year_matriculated', models.PositiveIntegerField(blank=True, null=True)),
                ('qualifications', models.TextField(blank=True, help_text='Qualifications, certificates or courses completed')),
                ('current_employment_status', models.CharField(blank=True, max_length=255)),
                ('availability_to_start', models.CharField(help_text='Example: Immediately, 2 weeks, 1 month', max_length=100)),
                ('has_drivers_license', models.BooleanField(default=False)),
                ('has_vehicle_access', models.BooleanField(default=False)),
                ('has_smartphone', models.BooleanField(default=True)),
                ('territory_understanding', models.TextField(help_text='Name areas, trader zones or business hubs within your territory where you believe The Daily Market could find clients.')),
                ('potential_client_types', models.TextField(help_text='What type of businesses or traders do you think would benefit most from The Daily Market?')),
                ('first_30_day_strategy', models.TextField(help_text='If you had to secure 10 recurring clients within 30 days, what would your approach be?')),
                ('cheaper_supplier_response', models.TextField(help_text='A client says another supplier is cheaper than The Daily Market. What would you do?')),
                ('client_retention_strategy', models.TextField(help_text='A client buys once and never orders again. How would you handle this situation?')),
                ('target_pressure_response', models.TextField(help_text='You have not reached your target and only 7 days remain in the month. What would you do?')),
                ('leadership_experience', models.TextField(blank=True, help_text='Have you ever managed people, coordinated a group or led a project? Explain.')),
                ('unsupervised_problem_solving', models.TextField(help_text='Describe a difficult problem you solved without supervision.')),
                ('performance_environment_understanding', models.TextField(help_text='What makes someone successful in a performance-based environment?')),
                ('startup_interest_reason', models.TextField(help_text='Why do you want to join a growing startup business instead of a traditional company?')),
                ('comfortable_performance_environment', models.BooleanField(default=True)),
                ('motivation', models.TextField(help_text='What motivates you most: income, growth opportunity, leadership, building something meaningful, or something else?')),
                ('introduction_video_link', models.URLField(blank=True, help_text='Optional: Link to a short introduction video (Google Drive, YouTube, Dropbox, etc.)')),
                ('application_status', models.CharField(choices=[('NEW', 'New'), ('UNDER_REVIEW', 'Under Review'), ('SHORTLISTED', 'Shortlisted'), ('INTERVIEW', 'Interview'), ('FIELD_TEST', 'Field Test'), ('REJECTED', 'Rejected'), ('APPROVED', 'Approved')], default='NEW', max_length=30)),
                ('territory_fit_score', models.IntegerField(blank=True, choices=[(1, '1 - Very Weak'), (2, '2 - Weak'), (3, '3 - Average'), (4, '4 - Strong'), (5, '5 - Exceptional')], null=True)),
                ('communication_score', models.IntegerField(blank=True, choices=[(1, '1 - Very Weak'), (2, '2 - Weak'), (3, '3 - Average'), (4, '4 - Strong'), (5, '5 - Exceptional')], null=True)),
                ('commercial_thinking_score', models.IntegerField(blank=True, choices=[(1, '1 - Very Weak'), (2, '2 - Weak'), (3, '3 - Average'), (4, '4 - Strong'), (5, '5 - Exceptional')], null=True)),
                ('leadership_potential_score', models.IntegerField(blank=True, choices=[(1, '1 - Very Weak'), (2, '2 - Weak'), (3, '3 - Average'), (4, '4 - Strong'), (5, '5 - Exceptional')], null=True)),
                ('startup_fit_score', models.IntegerField(blank=True, choices=[(1, '1 - Very Weak'), (2, '2 - Weak'), (3, '3 - Average'), (4, '4 - Strong'), (5, '5 - Exceptional')], null=True)),
                ('overall_rating', models.IntegerField(blank=True, choices=[(1, '1 - Very Weak'), (2, '2 - Weak'), (3, '3 - Average'), (4, '4 - Strong'), (5, '5 - Exceptional')], null=True)),
                ('evaluator_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.DeleteModel(
            name='SalesJobApplication',
        ),
    ]
