# Generated by Django 5.2.6 on 2026-09-05 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_jobapplication_delete_salesjobapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTaskSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('task_name', models.CharField(choices=[('supervisor_sales_report', 'Supervisor Sales Report'), ('rep_sales_report', 'Rep Sales Report')], max_length=100)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date', 'task_name'],
                'constraints': [models.UniqueConstraint(fields=('date', 'task_name'), name='unique_daily_task')],
            },
        ),
    ]
