# Generated by Django 5.2.6 on 2026-09-05 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_dailytaskschedule'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dailytaskschedule',
            name='unique_daily_task',
        ),
        migrations.RemoveField(
            model_name='dailytaskschedule',
            name='status',
        ),
        migrations.AlterField(
            model_name='dailytaskschedule',
            name='task_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AddConstraint(
            model_name='dailytaskschedule',
            constraint=models.UniqueConstraint(fields=('date', 'task_name'), name='unique_daily_task_schedule'),
        ),
    ]
