# Generated by Django 5.2.6 on 2026-09-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_remove_dailytaskschedule_unique_daily_task_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailytaskschedule',
            options={'ordering': ['-date', 'run_at', 'task_name']},
        ),
        migrations.RemoveField(
            model_name='dailytaskschedule',
            name='celery_task_id',
        ),
        migrations.AddField(
            model_name='dailytaskschedule',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailytaskschedule',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailytaskschedule',
            name='failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailytaskschedule',
            name='run_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailytaskschedule',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailytaskschedule',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
    ]
