# Generated by Django 5.2.6 on 2026-01-18 22:16

import deliveries.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryStopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=220)),
                ('sku', models.CharField(blank=True, max_length=64)),
                ('uom', models.CharField(blank=True, max_length=16)),
                ('planned_qty', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('loaded_qty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('delivered_qty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('shortage_reason', models.CharField(blank=True, max_length=220)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['stop_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DriverLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='PickingBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Human-friendly label, e.g. '2025-09-20 AM'.", max_length=140)),
                ('service_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('complete', 'Complete'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-service_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PickingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=220)),
                ('sku', models.CharField(blank=True, max_length=64)),
                ('uom', models.CharField(blank=True, max_length=16)),
                ('expected_qty', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('picked_qty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('expected_supplier_price', models.DecimalField(blank=True, decimal_places=2, help_text='Expected supplier price EXCL VAT at time of picking.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('actual_supplier_price', models.DecimalField(blank=True, decimal_places=2, help_text='Actual supplier price EXCL VAT as invoiced.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_picked', models.BooleanField(default=False, help_text='Supplier confirmed and quantity committed.')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['batch_id', 'order_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RunEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('START', 'Run Started'), ('STOP_ARRIVED', 'Arrived at Stop'), ('DELIVERED', 'Delivered'), ('FAILED', 'Delivery Failed')], max_length=20)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="Friendly name, e.g. 'Bakkie 1'", max_length=80)),
                ('registration_number', models.CharField(help_text='Vehicle registration number', max_length=20, unique=True)),
                ('vehicle_type', models.CharField(choices=[('bakkie', 'Bakkie'), ('van', 'Van'), ('truck', 'Truck'), ('bike', 'Motorbike'), ('other', 'Other')], default='bakkie', max_length=20)),
                ('capacity_kg', models.PositiveIntegerField(blank=True, help_text='Optional load capacity', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('maintenance', 'In Maintenance'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField(db_index=True)),
                ('name', models.CharField(blank=True, help_text="Optional label, e.g. '2025-09-27 AM'.", max_length=140)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('planned', 'Planned'), ('en_route', 'En Route'), ('paused', 'Paused'), ('complete', 'Complete'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('depot_label', models.CharField(blank=True, max_length=140)),
                ('depot_lat', models.FloatField(blank=True, null=True)),
                ('depot_lng', models.FloatField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('total_distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total_drive_min', models.PositiveIntegerField(blank=True, null=True)),
                ('stop_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_runs_created', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, help_text='Assigned driver (must be a system user with a DriverProfile).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-service_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('en_route', 'En Route'), ('delivered', 'Delivered'), ('failed', 'Failed Attempt'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('sequence', models.PositiveIntegerField(blank=True, help_text='Route order (1..N).', null=True)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address_line1', models.CharField(blank=True, max_length=220)),
                ('address_line2', models.CharField(blank=True, max_length=220)),
                ('suburb', models.CharField(blank=True, max_length=120)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('province', models.CharField(blank=True, max_length=120)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=120)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('service_min', models.PositiveIntegerField(default=5, help_text='Expected time on site.')),
                ('eta', models.DateTimeField(blank=True, null=True)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('drive_min', models.PositiveIntegerField(blank=True, null=True)),
                ('recipient_name', models.CharField(blank=True, max_length=160)),
                ('recipient_id_no', models.CharField(blank=True, max_length=80)),
                ('signature', models.ImageField(blank=True, null=True, upload_to=deliveries.models.pod_upload_to)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_notes', models.TextField(blank=True)),
                ('failed_reason', models.CharField(blank=True, max_length=220)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_stops_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['run_id', 'sequence', 'id'],
            },
        ),
    ]
