# Generated by Django 5.2.6 on 2026-01-18 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deliveries', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverystop',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_stops', to='orders.order'),
        ),
        migrations.AddField(
            model_name='deliverystop',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='deliveries.deliveryrun'),
        ),
        migrations.AddField(
            model_name='deliverystop',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_stops_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliverystopitem',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_stop_items', to='orders.orderitem'),
        ),
        migrations.AddField(
            model_name='deliverystopitem',
            name='stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='deliveries.deliverystop'),
        ),
        migrations.AddField(
            model_name='driverlocation',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='driverlocation',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='deliveries.deliveryrun'),
        ),
        migrations.AddField(
            model_name='pickingbatch',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='picking_batches_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pickingitem',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='deliveries.pickingbatch'),
        ),
        migrations.AddField(
            model_name='pickingitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picking_items', to='orders.order'),
        ),
        migrations.AddField(
            model_name='pickingitem',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picking_items', to='orders.orderitem'),
        ),
    ]
