# Generated by Django 5.2.6 on 2025-09-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryrun',
            name='name',
            field=models.CharField(blank=True, help_text="Optional label, e.g. '2025-09-27 AM'.", max_length=140),
        ),
    ]
