# Generated by Django 5.2.6 on 2026-01-18 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deliveries', '0002_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickingitem',
            name='supplier',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='picking_items', to='suppliers.supplier'),
        ),
        migrations.AddField(
            model_name='runevent',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='deliveries.deliveryrun'),
        ),
        migrations.AddField(
            model_name='runevent',
            name='stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='deliveries.deliverystop'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['status'], name='deliveries__status_f12a6e_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['vehicle_type'], name='deliveries__vehicle_e1da63_idx'),
        ),
        migrations.AddField(
            model_name='deliveryrun',
            name='vehicle',
            field=models.ForeignKey(blank=True, help_text='Assigned vehicle for this run', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_runs', to='deliveries.vehicle'),
        ),
        migrations.AddIndex(
            model_name='deliverystop',
            index=models.Index(fields=['run', 'status'], name='deliveries__run_id_52e156_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverystop',
            index=models.Index(fields=['order'], name='deliveries__order_i_823d97_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='deliverystop',
            unique_together={('run', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='deliverystopitem',
            unique_together={('stop', 'order_item')},
        ),
        migrations.AddIndex(
            model_name='driverlocation',
            index=models.Index(fields=['run', 'recorded_at'], name='deliveries__run_id_b46001_idx'),
        ),
        migrations.AddIndex(
            model_name='driverlocation',
            index=models.Index(fields=['driver', 'recorded_at'], name='deliveries__driver__b956db_idx'),
        ),
        migrations.AddIndex(
            model_name='pickingbatch',
            index=models.Index(fields=['service_date', 'status'], name='deliveries__service_21ae16_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pickingbatch',
            unique_together={('name', 'service_date')},
        ),
        migrations.AddIndex(
            model_name='pickingitem',
            index=models.Index(fields=['batch', 'order'], name='deliveries__batch_i_20e7f6_idx'),
        ),
        migrations.AddIndex(
            model_name='pickingitem',
            index=models.Index(fields=['supplier'], name='deliveries__supplie_38875c_idx'),
        ),
        migrations.AddIndex(
            model_name='pickingitem',
            index=models.Index(fields=['is_picked'], name='deliveries__is_pick_327586_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pickingitem',
            unique_together={('batch', 'order_item')},
        ),
        migrations.AddIndex(
            model_name='runevent',
            index=models.Index(fields=['run', 'event_type'], name='deliveries__run_id_748f2b_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryrun',
            index=models.Index(fields=['service_date', 'status'], name='deliveries__service_20c966_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryrun',
            index=models.Index(fields=['driver'], name='deliveries__driver__4c6512_idx'),
        ),
    ]
