# Generated by Django 5.2.6 on 2026-01-14 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0002_alter_deliveryrun_name'),
        ('suppliers', '0005_supplier_visible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickingitem',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Supplier committed to fulfilling this item for this batch.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='picking_items', to='suppliers.supplier'),
        ),
    ]
