# Generated by Django 5.2.6 on 2026-01-15 06:59

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0003_pickingitem_supplier'),
        ('orders', '0007_orderitem_unit_price_inc_and_more'),
        ('suppliers', '0005_supplier_visible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickingitem',
            name='actual_supplier_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual supplier price EXCL VAT as invoiced/received.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='pickingitem',
            name='expected_supplier_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='pickingitem',
            name='is_picked',
            field=models.BooleanField(default=False, help_text='Supplier confirmed and quantity committed.'),
        ),
        migrations.AlterField(
            model_name='pickingitem',
            name='supplier',
            field=models.ForeignKey(editable=False, help_text='Auto-assigned from product primary supplier at time of picking.', on_delete=django.db.models.deletion.PROTECT, related_name='picking_items', to='suppliers.supplier'),
        ),
        migrations.AddIndex(
            model_name='pickingitem',
            index=models.Index(fields=['supplier'], name='deliveries__supplie_38875c_idx'),
        ),
        migrations.AddIndex(
            model_name='pickingitem',
            index=models.Index(fields=['is_picked'], name='deliveries__is_pick_327586_idx'),
        ),
    ]
