# Generated by Django 5.2.6 on 2026-01-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='is_internal',
            field=models.BooleanField(default=True, help_text='True if this vehicle is owned/operated internally by the company'),
        ),
    ]
