# Generated by Django 5.2.6 on 2026-01-15 07:01

from django.db import migrations


def backfill_supplier(apps, schema_editor):
    PickingItem = apps.get_model("deliveries", "PickingItem")
    ProductPricing = apps.get_model("products", "ProductPricing")
    Supplier = apps.get_model("suppliers", "Supplier")

    for item in PickingItem.objects.filter(supplier__isnull=True):
        if not item.order_item_id:
            continue

        product = item.order_item.product
        if not product:
            continue

        pricing = (
            ProductPricing.objects
            .filter(product=product, is_active=True)
            .order_by("-is_primary", "id")
            .first()
        )

        if pricing:
            item.supplier_id = pricing.supplier_id
            item.save(update_fields=["supplier"])


class Migration(migrations.Migration):

    dependencies = [
        ("deliveries", "0004_pickingitem_actual_supplier_price_and_more"),
        
    ]


    operations = [
        migrations.RunPython(backfill_supplier),
    ]
