# Generated by Django 5.2.6 on 2026-01-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0004_vehicle_is_internal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalDeliveryRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'Partner Bakkie Rate'", max_length=100)),
                ('driver_per_km', models.DecimalField(decimal_places=2, help_text='Driver cost per km (partner)', max_digits=8)),
                ('assistant_per_km', models.DecimalField(decimal_places=2, help_text='Assistant cost per km (partner)', max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InternalDeliveryRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'Internal Bakkie Rate'", max_length=100)),
                ('driver_per_km', models.DecimalField(decimal_places=2, help_text='Driver cost per km', max_digits=8)),
                ('assistant_per_km', models.DecimalField(decimal_places=2, help_text='Assistant cost per km', max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
