# Generated by Django 5.2.6 on 2026-01-20 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0005_externaldeliveryrate_internaldeliveryrate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryrun',
            name='created_by',
        ),
        migrations.AddField(
            model_name='deliveryrun',
            name='assistant_rate_per_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='deliveryrun',
            name='driver_rate_per_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='deliveryrun',
            name='total_rate_per_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryrun',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deliveryrun',
            name='name',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='deliveryrun',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_runs', to='deliveries.vehicle'),
        ),
    ]
