# Generated by Django 5.2.6 on 2026-01-15 09:04

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0006_alter_pickingitem_expected_supplier_price_and_more'),
        ('suppliers', '0005_supplier_visible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickingitem',
            name='actual_supplier_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual supplier price EXCL VAT as invoiced.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='pickingitem',
            name='supplier',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='picking_items', to='suppliers.supplier'),
        ),
    ]
