# Generated by Django 5.2.6 on 2026-01-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0006_remove_deliveryrun_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryrun',
            name='assistant_total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Assistant cost = assistant_rate_per_km × total_distance_km', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='deliveryrun',
            name='driver_total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Driver cost = driver_rate_per_km × total_distance_km', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='deliveryrun',
            name='overall_total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total delivery cost (driver + assistant)', max_digits=10, null=True),
        ),
    ]
