# Generated by Django 5.2.6 on 2026-01-16 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0007_alter_pickingitem_actual_supplier_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='RunEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('START', 'Run Started'), ('STOP_ARRIVED', 'Arrived at Stop'), ('DELIVERED', 'Delivered'), ('FAILED', 'Delivery Failed')], max_length=20)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['recorded_at'],
            },
        ),
        migrations.RemoveField(
            model_name='deliveryrun',
            name='driver_name',
        ),
        migrations.AlterField(
            model_name='deliveryrun',
            name='depot_label',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='deliveryrun',
            name='driver',
            field=models.ForeignKey(blank=True, help_text='Assigned driver (must be a system user with a DriverProfile).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='deliveryrun',
            index=models.Index(fields=['driver'], name='deliveries__driver__4c6512_idx'),
        ),
        migrations.AddField(
            model_name='driverlocation',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='driverlocation',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='deliveries.deliveryrun'),
        ),
        migrations.AddField(
            model_name='runevent',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='deliveries.deliveryrun'),
        ),
        migrations.AddField(
            model_name='runevent',
            name='stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='deliveries.deliverystop'),
        ),
        migrations.AddIndex(
            model_name='driverlocation',
            index=models.Index(fields=['run', 'recorded_at'], name='deliveries__run_id_b46001_idx'),
        ),
        migrations.AddIndex(
            model_name='driverlocation',
            index=models.Index(fields=['driver', 'recorded_at'], name='deliveries__driver__b956db_idx'),
        ),
        migrations.AddIndex(
            model_name='runevent',
            index=models.Index(fields=['run', 'event_type'], name='deliveries__run_id_748f2b_idx'),
        ),
    ]
