# Generated by Django 5.2.6 on 2026-02-10 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0007_deliveryrun_assistant_total_cost_and_more'),
        ('orders', '0003_alter_order_status'),
        ('suppliers', '0002_supplier_delivery_lat_supplier_delivery_lng_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='deliverystop',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='deliverystop',
            name='stop_type',
            field=models.CharField(choices=[('START', 'Start / Departure'), ('SUPPLIER', 'Supplier Pickup'), ('CUSTOMER', 'Customer Delivery'), ('RETURN', 'Return to Depot')], db_index=True, default='CUSTOMER', max_length=20),
        ),
        migrations.AddField(
            model_name='deliverystop',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_stops', to='suppliers.supplier'),
        ),
        migrations.AlterField(
            model_name='deliverystop',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_stops', to='orders.order'),
        ),
        migrations.AddConstraint(
            model_name='deliverystop',
            constraint=models.UniqueConstraint(condition=models.Q(('order__isnull', False)), fields=('run', 'order'), name='unique_order_per_run'),
        ),
        migrations.AddConstraint(
            model_name='deliverystop',
            constraint=models.UniqueConstraint(condition=models.Q(('stop_type', 'SUPPLIER'), ('supplier__isnull', False)), fields=('run', 'supplier'), name='unique_supplier_per_run'),
        ),
    ]
