# Generated by Django 5.2.6 on 2026-02-11 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0008_alter_deliverystop_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='deliverystop',
            name='deliveries__run_id_52e156_idx',
        ),
        migrations.RemoveIndex(
            model_name='deliverystop',
            name='deliveries__order_i_823d97_idx',
        ),
        migrations.AlterField(
            model_name='deliverystop',
            name='service_min',
            field=models.PositiveIntegerField(default=5, help_text='Expected time on site (minutes).'),
        ),
    ]
