# Generated by Django 5.2.6 on 2026-01-17 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0008_driverlocation_runevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverystop',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverystop',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
