# Generated by Django 5.2.6 on 2026-07-08 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0009_remove_deliverystop_deliveries__run_id_52e156_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverystop',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('en_route', 'En Route'), ('awaiting_completion', 'Awaiting Completion'), ('delivered', 'Delivered'), ('failed', 'Failed Attempt'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
    ]
