# Generated by Django 5.2.6 on 2026-01-18 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0009_deliverystop_ended_at_deliverystop_started_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="Friendly name, e.g. 'Bakkie 1'", max_length=80)),
                ('registration_number', models.CharField(help_text='Vehicle registration number', max_length=20, unique=True)),
                ('vehicle_type', models.CharField(choices=[('bakkie', 'Bakkie'), ('van', 'Van'), ('truck', 'Truck'), ('bike', 'Motorbike'), ('other', 'Other')], default='bakkie', max_length=20)),
                ('capacity_kg', models.PositiveIntegerField(blank=True, help_text='Optional load capacity', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('maintenance', 'In Maintenance'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['label'],
                'indexes': [models.Index(fields=['status'], name='deliveries__status_f12a6e_idx'), models.Index(fields=['vehicle_type'], name='deliveries__vehicle_e1da63_idx')],
            },
        ),
    ]
