# Generated by Django 5.2.6 on 2026-07-08 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0010_alter_deliverystop_status'),
        ('suppliers', '0002_supplier_delivery_lat_supplier_delivery_lng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryrun',
            name='start_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryrun',
            name='start_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryrun',
            name='start_location_label',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='deliveryrun',
            name='start_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_runs_started_from', to='suppliers.supplier'),
        ),
    ]
