# Generated by Django 5.2.6 on 2026-01-18 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0010_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryrun',
            name='vehicle_label',
        ),
        migrations.AddField(
            model_name='deliveryrun',
            name='vehicle',
            field=models.ForeignKey(blank=True, help_text='Assigned vehicle for this run', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_runs', to='deliveries.vehicle'),
        ),
    ]
