# Generated by Django 5.2.6 on 2026-07-12 14:53

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0011_deliveryrun_start_lat_deliveryrun_start_lng_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickingitem',
            name='actual_supplier_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual supplier price INCL VAT as invoiced.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='pickingitem',
            name='expected_supplier_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Expected supplier price INCL VAT at time of picking.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
