# Generated by Django 5.2.6 on 2026-09-03 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0012_alter_pickingitem_actual_supplier_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverystop',
            name='stop_type',
            field=models.CharField(choices=[('START', 'Start / Departure'), ('SUPPLIER', 'Supplier Pickup'), ('CUSTOMER', 'Customer Delivery'), ('RETURN', 'Return to Driver')], db_index=True, default='CUSTOMER', max_length=20),
        ),
    ]
