# Generated by Django 5.2.6 on 2026-09-12 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0033_enduser'),
        ('deliveries', '0013_alter_deliverystop_stop_type'),
        ('orders', '0012_order_end_user_quotation_end_user_and_more'),
        ('suppliers', '0002_supplier_delivery_lat_supplier_delivery_lng_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverystop',
            name='end_user',
            field=models.ForeignKey(blank=True, help_text='End user receiving the delivery, where applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_stops', to='clients.enduser'),
        ),
        migrations.AddIndex(
            model_name='deliverystop',
            index=models.Index(fields=['end_user', 'status'], name='deliveries__end_use_922d0d_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverystop',
            index=models.Index(fields=['run', 'end_user'], name='deliveries__run_id_523f3a_idx'),
        ),
    ]
