# Generated by Django 5.2.6 on 2026-09-28 02:55

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0015_deliveryrun_completed_by_deliveryrun_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='maximum_units',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Maximum number of individual units expected from the base quantity. Use the same value for an exact count.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='inventory',
            name='minimum_units',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Minimum number of individual units expected from the base quantity.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
