# Generated by Django 5.2.6 on 2026-01-18 22:16

import django.core.validators
import django.db.models.deletion
import products.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack_size', models.DecimalField(decimal_places=2, max_digits=8)),
                ('uom', models.CharField(choices=[('EA', 'Each'), ('KG', 'Kilogram'), ('L', 'Litre'), ('PK', 'Pack'), ('BOX', 'Box')], default='KG', max_length=8)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('sku', models.CharField(blank=True, max_length=50, null=True)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/variants/')),
                ('wholesale_price_override', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('retail_price_override', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('wholesale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('retail_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('scales_with_pack', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['product__name', 'pack_size'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('abbreviation', models.CharField(blank=True, db_index=True, help_text='3-letter code auto-generated from name (you can override).', max_length=3)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent category (leave blank for top-level categories).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='products.category')),
            ],
            options={
                'ordering': ['parent__name', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_no', models.PositiveIntegerField(db_index=True, help_text='External Product Number from Excel (stable identifier)', unique=True)),
                ('name', models.CharField(max_length=200)),
                ('sku', models.CharField(blank=True, max_length=64, null=True)),
                ('slug', models.SlugField(blank=True, max_length=220, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=products.models.product_image_path)),
                ('uom', models.CharField(choices=[('EA', 'Each'), ('KG', 'Kilogram'), ('L', 'Litre'), ('PK', 'Pack'), ('BOX', 'Box')], default='EA', max_length=8)),
                ('description', models.TextField(blank=True)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('wholesale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('retail_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('retail_margin_pct', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Select the most specific category (e.g. Beef, Chicken).', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_price_excl', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Supplier price EXCL VAT (R).', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('supplier_vat_percent', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('supplier_price_input', models.DecimalField(blank=True, decimal_places=2, help_text='Raw price as entered (EXCL or INCL).', max_digits=12, null=True)),
                ('supplier_price_is_inclusive', models.BooleanField(default=False, help_text='Tick if supplier_price_input is VAT inclusive.')),
                ('wholesale_margin_percent', models.DecimalField(choices=[(Decimal('10.00'), '10%'), (Decimal('12.50'), '12.50%'), (Decimal('15.00'), '15%'), (Decimal('17.50'), '17.50%'), (Decimal('20.00'), '20%'), (Decimal('22.50'), '22.50%'), (Decimal('25.00'), '25%'), (Decimal('27.50'), '27.50%'), (Decimal('30.00'), '30%'), (Decimal('32.50'), '32.50%'), (Decimal('35.00'), '35%'), (Decimal('37.50'), '37.50%'), (Decimal('40.00'), '40%')], decimal_places=2, default=Decimal('15.00'), max_digits=6)),
                ('wholesale_vat_percent', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('retail_margin_percent', models.DecimalField(choices=[(Decimal('10.00'), '10%'), (Decimal('12.50'), '12.50%'), (Decimal('15.00'), '15%'), (Decimal('17.50'), '17.50%'), (Decimal('20.00'), '20%'), (Decimal('22.50'), '22.50%'), (Decimal('25.00'), '25%'), (Decimal('27.50'), '27.50%'), (Decimal('30.00'), '30%'), (Decimal('32.50'), '32.50%'), (Decimal('35.00'), '35%'), (Decimal('37.50'), '37.50%'), (Decimal('40.00'), '40%')], decimal_places=2, default=Decimal('25.00'), max_digits=6)),
                ('retail_vat_percent', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('is_primary', models.BooleanField(default=False, help_text='If true, sync prices to Product.')),
                ('skip_variant_sync', models.BooleanField(default=False, help_text='Skip pushing prices to variants on this save.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rows', to='products.product')),
            ],
            options={
                'ordering': ['supplier__name'],
            },
        ),
    ]
