# Generated by Django 5.2.6 on 2026-01-18 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpricing',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_pricing', to='suppliers.supplier'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='products_ca_slug_da4386_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active'], name='products_ca_is_acti_a2d000_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['abbreviation'], name='products_ca_abbrevi_dd70e4_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent'], name='products_ca_parent__f3c24e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('parent', 'name')},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='products_pr_sku_ca0cdc_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='products_pr_slug_3edc0c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='products_pr_categor_9edb3d_idx'),
        ),
        migrations.AddIndex(
            model_name='productpricing',
            index=models.Index(fields=['product', 'supplier'], name='products_pr_product_fe25fd_idx'),
        ),
        migrations.AddIndex(
            model_name='productpricing',
            index=models.Index(fields=['is_active'], name='products_pr_is_acti_324529_idx'),
        ),
        migrations.AddConstraint(
            model_name='productpricing',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('product',), name='uniq_primary_pricing_per_product'),
        ),
        migrations.AlterUniqueTogether(
            name='productpricing',
            unique_together={('product', 'supplier')},
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product', 'pack_size'], name='products_pr_product_af046c_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['slug'], name='products_pr_slug_d83465_idx'),
        ),
    ]
