# Generated by Django 5.2.6 on 2026-07-05 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_special',
            field=models.BooleanField(default=False, help_text='Tick if this product is currently on special.'),
        ),
        migrations.AddField(
            model_name='product',
            name='old_wholesale_price_inc',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Previous wholesale selling price INCLUDING VAT.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='special_label',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
