# Generated by Django 5.2.6 on 2026-07-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_is_special_product_old_wholesale_price_inc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='visible',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], db_index=True, default='YES', help_text='Controls whether this product is visible in the shop and catalog.', max_length=3),
        ),
    ]
