# Generated by Django 5.2.6 on 2025-09-14 08:40

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_initial'),
        ('suppliers', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sku', models.CharField(max_length=64, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('uom', models.CharField(choices=[('EA', 'Each'), ('KG', 'Kilogram'), ('L', 'Litre'), ('PK', 'Pack'), ('BOX', 'Box')], default='EA', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_price_excl', models.DecimalField(decimal_places=2, help_text='Supplier price excluding VAT (R).', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('supplier_vat_percent', models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Supplier VAT % (usually 15%).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('company_margin_percent', models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Company margin % applied to supplier price incl.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('company_vat_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Company VAT % for selling (0% if not charging VAT).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rows', to='products.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_pricing', to='suppliers.supplier')),
            ],
            options={
                'ordering': ['supplier__name'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='products_pr_sku_ca0cdc_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='products_pr_slug_3edc0c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='products_pr_categor_9edb3d_idx'),
        ),
        migrations.AddIndex(
            model_name='productpricing',
            index=models.Index(fields=['product', 'supplier'], name='products_pr_product_fe25fd_idx'),
        ),
        migrations.AddIndex(
            model_name='productpricing',
            index=models.Index(fields=['is_active'], name='products_pr_is_acti_324529_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productpricing',
            unique_together={('product', 'supplier')},
        ),
    ]
