# Generated by Django 5.2.6 on 2025-09-28 16:38

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_productpricing_and_more'),
        ('suppliers', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='created_at',
            new_name='reated_at',
        ),
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='retail_margin_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=6),
        ),
        migrations.AddField(
            model_name='product',
            name='retail_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='wholesale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='productpricing',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productpricing',
            name='company_margin_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Company margin % applied to supplier price (ex VAT).', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('1000.00'))]),
        ),
        migrations.AlterField(
            model_name='productpricing',
            name='company_vat_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Company VAT % (0% if not charging VAT).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
        migrations.AlterField(
            model_name='productpricing',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_pricing', to='suppliers.supplier'),
        ),
    ]
