# Generated by Django 5.2.6 on 2026-07-13 14:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpricing',
            name='retail_margin_percent',
            field=models.DecimalField(choices=[(Decimal('0.00'), '0%'), (Decimal('5.00'), '5%'), (Decimal('10.00'), '10%'), (Decimal('12.50'), '12.50%'), (Decimal('15.00'), '15%'), (Decimal('17.50'), '17.50%'), (Decimal('20.00'), '20%'), (Decimal('22.50'), '22.50%'), (Decimal('25.00'), '25%'), (Decimal('27.50'), '27.50%'), (Decimal('30.00'), '30%'), (Decimal('32.50'), '32.50%'), (Decimal('35.00'), '35%'), (Decimal('37.50'), '37.50%'), (Decimal('40.00'), '40%')], decimal_places=2, default=Decimal('25.00'), max_digits=6),
        ),
        migrations.AlterField(
            model_name='productpricing',
            name='wholesale_margin_percent',
            field=models.DecimalField(choices=[(Decimal('0.00'), '0%'), (Decimal('5.00'), '5%'), (Decimal('10.00'), '10%'), (Decimal('12.50'), '12.50%'), (Decimal('15.00'), '15%'), (Decimal('17.50'), '17.50%'), (Decimal('20.00'), '20%'), (Decimal('22.50'), '22.50%'), (Decimal('25.00'), '25%'), (Decimal('27.50'), '27.50%'), (Decimal('30.00'), '30%'), (Decimal('32.50'), '32.50%'), (Decimal('35.00'), '35%'), (Decimal('37.50'), '37.50%'), (Decimal('40.00'), '40%')], decimal_places=2, default=Decimal('15.00'), max_digits=6),
        ),
    ]
