# Generated by Django 5.2.6 on 2026-08-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productpricing_retail_margin_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_no',
            field=models.CharField(db_index=True, help_text='Unique Product ID: Category-Subcategory-Product', max_length=11, unique=True),
        ),
    ]
