# Generated by Django 5.2.6 on 2025-09-28 17:27

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_created_at_product_reated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='reated_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='productpricing',
            name='company_margin_percent',
        ),
        migrations.RemoveField(
            model_name='productpricing',
            name='company_vat_percent',
        ),
        migrations.AddField(
            model_name='productpricing',
            name='retail_margin_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('25.00'), help_text='Margin % applied on supplier EXCL to get retail EXCL.', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('-100.00')), django.core.validators.MaxValueValidator(Decimal('1000.00'))]),
        ),
        migrations.AddField(
            model_name='productpricing',
            name='retail_vat_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='VAT % used for retail INCL.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
        migrations.AddField(
            model_name='productpricing',
            name='wholesale_margin_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Margin % applied on supplier EXCL to get wholesale EXCL.', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('-100.00')), django.core.validators.MaxValueValidator(Decimal('1000.00'))]),
        ),
        migrations.AddField(
            model_name='productpricing',
            name='wholesale_vat_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='VAT % used for wholesale INCL.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
        migrations.AlterField(
            model_name='productpricing',
            name='supplier_price_excl',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Supplier price excluding VAT (R).', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
