# Generated by Django 5.2.6 on 2025-09-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_reated_at_product_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='abbreviation',
            field=models.CharField(blank=True, db_index=True, help_text='Short code auto-generated from name (you can override).', max_length=12),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['abbreviation'], name='products_ca_abbrevi_dd70e4_idx'),
        ),
    ]
