# Generated by Django 5.2.6 on 2026-08-16 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_product_no'),
        ('suppliers', '0002_supplier_delivery_lat_supplier_delivery_lng_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('INITIAL', 'Initial Price'), ('INCREASE', 'Price Increase'), ('DECREASE', 'Price Decrease'), ('MIXED', 'Mixed Price Change')], max_length=10)),
                ('previous_cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('new_cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cost_change', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('previous_wholesale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('new_wholesale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('wholesale_change', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('previous_retail_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('new_retail_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('retail_change', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='products.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_price_history', to='suppliers.supplier')),
            ],
            options={
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['product', '-changed_at'], name='products_pr_product_40293a_idx'), models.Index(fields=['supplier', '-changed_at'], name='products_pr_supplie_c72881_idx'), models.Index(fields=['change_type'], name='products_pr_change__e8b5ee_idx')],
            },
        ),
    ]
