# Generated by Django 5.2.6 on 2026-08-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productpricehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_no',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='Business category number, e.g. 009.', null=True),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('parent', 'category_no'), name='unique_category_number_per_parent'),
        ),
    ]
