# Generated by Django 5.2.6 on 2025-09-28 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_category_abbreviation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='abbreviation',
            field=models.CharField(blank=True, db_index=True, help_text='3-letter code auto-generated from name (you can override).', max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
    ]
