# Generated by Django 5.2.6 on 2026-08-24 19:03

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_category_category_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpricing',
            name='retail_margin_percent',
            field=models.DecimalField(choices=[(Decimal('0.00'), '0%'), (Decimal('5.00'), '5%'), (Decimal('7.50'), '7.50%'), (Decimal('10.00'), '10%'), (Decimal('12.50'), '12.50%'), (Decimal('15.00'), '15%'), (Decimal('17.50'), '17.50%'), (Decimal('20.00'), '20%'), (Decimal('22.50'), '22.50%'), (Decimal('25.00'), '25%'), (Decimal('27.50'), '27.50%'), (Decimal('30.00'), '30%'), (Decimal('32.50'), '32.50%'), (Decimal('35.00'), '35%'), (Decimal('37.50'), '37.50%'), (Decimal('40.00'), '40%')], decimal_places=2, default=Decimal('25.00'), max_digits=6),
        ),
        migrations.AlterField(
            model_name='productpricing',
            name='wholesale_margin_percent',
            field=models.DecimalField(choices=[(Decimal('0.00'), '0%'), (Decimal('5.00'), '5%'), (Decimal('7.50'), '7.50%'), (Decimal('10.00'), '10%'), (Decimal('12.50'), '12.50%'), (Decimal('15.00'), '15%'), (Decimal('17.50'), '17.50%'), (Decimal('20.00'), '20%'), (Decimal('22.50'), '22.50%'), (Decimal('25.00'), '25%'), (Decimal('27.50'), '27.50%'), (Decimal('30.00'), '30%'), (Decimal('32.50'), '32.50%'), (Decimal('35.00'), '35%'), (Decimal('37.50'), '37.50%'), (Decimal('40.00'), '40%')], decimal_places=2, default=Decimal('15.00'), max_digits=6),
        ),
        migrations.CreateModel(
            name='ProductKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_description', models.TextField(blank=True, help_text='What is this product? Provide a clear definition for the sales representative.')),
                ('usage_application', models.TextField(blank=True, help_text='What meals, menu items or applications is this product used for? Enter N/A if not applicable.')),
                ('yield_portion_information', models.TextField(blank=True, help_text='Provide useful yield, portion or serving information. Enter N/A if not applicable.')),
                ('variants_not_applicable', models.BooleanField(default=False, help_text='Tick this if the product has no relevant knowledge variants. This counts the Variants section as complete.')),
                ('why_choose_tdm', models.TextField(blank=True, help_text='Why should the customer choose this product from The Daily Market?')),
                ('key_takeaways', models.TextField(blank=True, help_text='The most important things the sales representative must remember about this product.')),
                ('is_approved', models.BooleanField(default=False, help_text='Indicates whether the Product Knowledge profile has been reviewed and approved.')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(help_text='Product this knowledge profile belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='knowledge', to='products.product')),
            ],
            options={
                'ordering': ['product__name'],
            },
        ),
        migrations.CreateModel(
            name='ProductKnowledgeAlternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(help_text='Alternative brand.', max_length=150)),
                ('product_name', models.CharField(blank=True, help_text='Specific alternative product, if known.', max_length=200)),
                ('notes', models.TextField(blank=True, help_text='Why customers may use this alternative.')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('product_knowledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_alternatives', to='products.productknowledge')),
            ],
            options={
                'ordering': ['sort_order', 'brand', 'product_name'],
            },
        ),
        migrations.CreateModel(
            name='ProductKnowledgeBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit', models.CharField(help_text='Short name of the product benefit.', max_length=200)),
                ('explanation', models.TextField(blank=True, help_text='Explain why this benefit matters to the customer.')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('product_knowledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_benefits', to='products.productknowledge')),
            ],
            options={
                'ordering': ['sort_order', 'benefit'],
            },
        ),
        migrations.CreateModel(
            name='ProductKnowledgeBusinessType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_type', models.CharField(help_text='Type of food business that uses this product.', max_length=150)),
                ('notes', models.TextField(blank=True, help_text='Optional explanation of why this business type uses the product.')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('product_knowledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_business_types', to='products.productknowledge')),
            ],
            options={
                'ordering': ['sort_order', 'business_type'],
            },
        ),
        migrations.CreateModel(
            name='ProductKnowledgeCompetitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competitor_brand', models.CharField(help_text='Competitor brand.', max_length=150)),
                ('competitor_product', models.CharField(blank=True, help_text='Specific competitor product, if known.', max_length=200)),
                ('why_customer_uses_it', models.TextField(help_text='Why customers currently choose this competitor.')),
                ('tdm_positioning', models.TextField(help_text='How the sales representative should position The Daily Market against this competitor.')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('product_knowledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_competitors', to='products.productknowledge')),
            ],
            options={
                'ordering': ['sort_order', 'competitor_brand', 'competitor_product'],
            },
        ),
        migrations.CreateModel(
            name='ProductKnowledgeObjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objection', models.TextField(help_text='Common objection the customer may raise.')),
                ('response', models.TextField(help_text='Recommended response for the sales representative.')),
                ('notes', models.TextField(blank=True, help_text='Additional guidance for the representative.')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('product_knowledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_objections', to='products.productknowledge')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductKnowledgeQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='Question the sales representative should ask.')),
                ('purpose', models.TextField(blank=True, help_text='Why should the representative ask this question?')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('product_knowledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_questions', to='products.productknowledge')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductKnowledgeVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_name', models.CharField(help_text='Name of the product knowledge variant.', max_length=150)),
                ('description', models.TextField(help_text='Explain what this variant is and what makes it different.')),
                ('best_suited_for', models.TextField(help_text='Which customers, businesses, meals or applications are best suited to this variant?')),
                ('customer_benefit', models.TextField(help_text='What benefit does this particular variant provide to the customer?')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('product_knowledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_variants', to='products.productknowledge')),
            ],
            options={
                'ordering': ['sort_order', 'variant_name'],
            },
        ),
    ]
