# Generated by Django 5.2.6 on 2025-10-27 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_category_abbreviation_alter_product_sku'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack_size', models.DecimalField(decimal_places=2, max_digits=8)),
                ('uom', models.CharField(choices=[('EA', 'Each'), ('KG', 'Kilogram'), ('L', 'Litre'), ('PK', 'Pack'), ('BOX', 'Box')], default='KG', max_length=8)),
                ('name', models.CharField(blank=True, help_text='Optional display name; blank -> auto from pack_size + UOM.', max_length=200)),
                ('sku', models.CharField(blank=True, max_length=64, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/variants/')),
                ('wholesale_price_override', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('retail_price_override', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('scales_with_pack', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
            ],
            options={
                'ordering': ['product__name', 'pack_size'],
                'indexes': [models.Index(fields=['product', 'pack_size'], name='products_pr_product_af046c_idx'), models.Index(fields=['slug'], name='products_pr_slug_d83465_idx')],
            },
        ),
    ]
