# Generated by Django 5.2.6 on 2026-08-27 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_productpricing_retail_margin_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='special_wholesale_price_inc',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Special wholesale selling price INCLUDING VAT.', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='special_label',
            field=models.CharField(blank=True, default='SPECIAL', max_length=50),
        ),
    ]
