# Generated by Django 5.2.6 on 2025-11-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_productvariant'),
        ('suppliers', '0005_supplier_visible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpricing',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='If true, this row sets Product wholesale/retail base prices.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddConstraint(
            model_name='productpricing',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('product',), name='uniq_primary_pricing_per_product'),
        ),
    ]
