# Generated by Django 5.2.6 on 2026-09-24 05:14

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_special_wholesale_price_inc_and_more'),
        ('suppliers', '0002_supplier_delivery_lat_supplier_delivery_lng_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Procurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procurement_number', models.CharField(db_index=True, help_text='Unique TDM procurement reference.', max_length=40, unique=True)),
                ('procurement_date', models.DateField(db_index=True)),
                ('wave', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], db_index=True, help_text='Procurement cycle: AM or PM.', max_length=2)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurements_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurements_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-procurement_date', '-wave', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProcurementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_quantity', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('procurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.procurement')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procurement_items', to='products.product')),
            ],
            options={
                'ordering': ['product__name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('order_date', models.DateField(db_index=True)),
                ('expected_delivery_date', models.DateField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('sent', 'Sent to Supplier'), ('partially_received', 'Partially Received'), ('received', 'Received'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=25)),
                ('supplier_reference', models.CharField(blank=True, help_text="Supplier's own reference, if provided.", max_length=100)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders_created', to=settings.AUTH_USER_MODEL)),
                ('procurement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='products.procurement')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='suppliers.supplier')),
            ],
            options={
                'ordering': ['-order_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_quantity', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('expected_unit_cost_excl', models.DecimalField(blank=True, decimal_places=2, help_text='Expected supplier cost excluding VAT.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('procurement_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_items', to='products.procurementitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_items', to='products.product')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.purchaseorder')),
            ],
            options={
                'ordering': ['product__name', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='procurement',
            index=models.Index(fields=['procurement_date', 'wave', 'status'], name='procurement_date_wave_status'),
        ),
        migrations.AddConstraint(
            model_name='procurement',
            constraint=models.UniqueConstraint(fields=('procurement_date', 'wave'), name='unique_procurement_per_day_wave'),
        ),
        migrations.AddIndex(
            model_name='procurementitem',
            index=models.Index(fields=['procurement', 'product'], name='procurement_item_product_idx'),
        ),
        migrations.AddConstraint(
            model_name='procurementitem',
            constraint=models.UniqueConstraint(fields=('procurement', 'product'), name='unique_product_per_procurement'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['procurement', 'supplier'], name='po_procurement_supplier_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['supplier', 'status'], name='po_supplier_status_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['order_date', 'status'], name='po_order_date_status_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderitem',
            index=models.Index(fields=['purchase_order', 'product'], name='po_item_order_product_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderitem',
            index=models.Index(fields=['procurement_item'], name='po_item_procurement_idx'),
        ),
    ]
