# Generated by Django 5.2.6 on 2025-11-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_productpricing_is_primary_alter_product_sku_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpricing',
            name='skip_variant_sync',
            field=models.BooleanField(default=False, help_text='If ticked, updating product prices from this row will NOT push prices to variants for this save.'),
        ),
    ]
