# Generated by Django 5.2.6 on 2026-09-27 10:47

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_procurement_procurementitem_purchaseorder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductKnowledgeUnitEconomics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_applicable', models.BooleanField(default=False, help_text='Tick this when it is useful to calculate the approximate cost of an individual unit, piece or item from this product.')),
                ('base_quantity', models.DecimalField(decimal_places=3, default=Decimal('1.000'), help_text='Quantity of the product used as the calculation base, e.g. 1 KG or 1 BOX.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('base_uom', models.CharField(choices=[('EA', 'Each'), ('KG', 'Kilogram'), ('L', 'Litre'), ('PK', 'Pack'), ('BOX', 'Box')], default='KG', help_text='Unit of measure for the calculation base.', max_length=8)),
                ('unit_name', models.CharField(help_text='What individual unit is being costed, e.g. Wing, Russian, Burger Patty.', max_length=100)),
                ('minimum_units', models.DecimalField(decimal_places=2, help_text='Minimum number of individual units expected from the base quantity.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('maximum_units', models.DecimalField(decimal_places=2, help_text='Maximum number of individual units expected from the base quantity. Use the same value for an exact count.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('knowledge', models.OneToOneField(help_text='Product Knowledge profile this unit-economics information belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='unit_economics', to='products.productknowledge')),
            ],
            options={
                'verbose_name': 'Product Knowledge Unit Economics',
                'verbose_name_plural': 'Product Knowledge Unit Economics',
            },
        ),
    ]
