# Generated by Django 5.2.6 on 2025-12-07 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_productpricing_skip_variant_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpricing',
            name='supplier_price_input',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional: raw supplier price as entered on the invoice (EXCL or INCL depending on the checkbox).', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='productpricing',
            name='supplier_price_is_inclusive',
            field=models.BooleanField(default=False, help_text='Tick if the entered supplier price is VAT inclusive.'),
        ),
    ]
