# Generated by Django 5.2.6 on 2025-12-07 10:46

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_productpricing_supplier_price_input_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpricing',
            name='retail_margin_percent',
            field=models.DecimalField(choices=[(Decimal('15.00'), '15%'), (Decimal('17.50'), '17.50%'), (Decimal('20.00'), '20%'), (Decimal('22.50'), '22.50%'), (Decimal('25.00'), '25%'), (Decimal('27.50'), '27.50%'), (Decimal('30.00'), '30%'), (Decimal('32.50'), '32.50%'), (Decimal('35.00'), '35%')], decimal_places=2, default=Decimal('25.00'), max_digits=6),
        ),
        migrations.AlterField(
            model_name='productpricing',
            name='retail_vat_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='VAT % used for retail INCL.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
        migrations.AlterField(
            model_name='productpricing',
            name='wholesale_margin_percent',
            field=models.DecimalField(choices=[(Decimal('15.00'), '15%'), (Decimal('17.50'), '17.50%'), (Decimal('20.00'), '20%'), (Decimal('22.50'), '22.50%'), (Decimal('25.00'), '25%'), (Decimal('27.50'), '27.50%'), (Decimal('30.00'), '30%'), (Decimal('32.50'), '32.50%'), (Decimal('35.00'), '35%')], decimal_places=2, default=Decimal('15.00'), max_digits=6),
        ),
        migrations.AlterField(
            model_name='productpricing',
            name='wholesale_vat_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='VAT % used for wholesale INCL.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
    ]
