# Generated by Django 5.2.6 on 2025-12-14 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_category_options_category_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_no',
            field=models.PositiveIntegerField(
                null=True,
                blank=True,
                db_index=True,
                unique=True,
                help_text='External Product Number from Excel (stable identifier)',
            ),
        ),

    ]
