# Generated by Django 5.2.6 on 2025-12-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_product_product_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_no',
            field=models.PositiveIntegerField(db_index=True, help_text='External Product Number from Excel (stable identifier)', unique=True),
        ),
    ]
