# Generated by Django 5.2.6 on 2025-12-15 03:43

import django.core.validators
import products.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_product_product_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.product_image_path),
        ),
        migrations.AlterField(
            model_name='productpricing',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='If true, sync prices to Product.'),
        ),
        migrations.AlterField(
            model_name='productpricing',
            name='retail_vat_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
        migrations.AlterField(
            model_name='productpricing',
            name='skip_variant_sync',
            field=models.BooleanField(default=False, help_text='Skip pushing prices to variants on this save.'),
        ),
        migrations.AlterField(
            model_name='productpricing',
            name='supplier_price_excl',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Supplier price EXCL VAT (R).', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='productpricing',
            name='supplier_price_input',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Raw price as entered (EXCL or INCL).', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='productpricing',
            name='supplier_price_is_inclusive',
            field=models.BooleanField(default=False, help_text='Tick if supplier_price_input is VAT inclusive.'),
        ),
        migrations.AlterField(
            model_name='productpricing',
            name='supplier_vat_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
        migrations.AlterField(
            model_name='productpricing',
            name='wholesale_vat_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
    ]
