# Generated by Django 5.2.6 on 2026-01-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_productpricing_retail_margin_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='retail_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='wholesale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
