# Generated by Django 5.2.6 on 2026-01-03 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_productvariant_retail_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
